import { query, run, initDatabase } from './database'
import { wordService } from './sqlite-api'
import { getStoredToken } from './supabase'
import { HSKLevel, HSKVersion, Word } from '@/types'
import {
  SentenceDifficulty,
  SentenceExercise,
  WritingAttemptRecord,
  WritingDirection,
  WritingQuestion,
  WritingScope,
  WritingSessionRecord,
  WritingStats,
  WritingWeakWord,
} from '@/types/writing'

let initialized = false
async function ensureDb(): Promise<void> {
  if (!initialized) {
    await initDatabase()
    initialized = true
  }
}

function newId(prefix: string): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return `${prefix}_${crypto.randomUUID()}`
  }
  return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`
}

function levelsFor(scope: WritingScope, level: HSKLevel): HSKLevel[] {
  return scope === 'cumulative'
    ? ([1, 2, 3, 4].filter((l) => l <= level) as HSKLevel[])
    : [level]
}

function shuffle<T>(items: T[]): T[] {
  const copy = [...items]
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[copy[i], copy[j]] = [copy[j], copy[i]]
  }
  return copy
}

export interface BuildQuestionsInput {
  direction: WritingDirection
  hskLevel: HSKLevel
  scope: WritingScope
  order: 'sequential' | 'random'
  questionCount: number
  version?: HSKVersion | null
}

/** Build the question list for a vocabulary writing session. */
export async function buildVocabularyQuestions(input: BuildQuestionsInput): Promise<WritingQuestion[]> {
  await ensureDb()
  const levels = new Set(levelsFor(input.scope, input.hskLevel))

  const all = await wordService.getAll(input.version ?? undefined)
  let pool = all.filter((w) => levels.has(w.hsk_level) && w.chinese.trim().length > 0)

  if (input.order === 'random') pool = shuffle(pool)

  const limit = input.questionCount > 0 ? input.questionCount : pool.length
  const selected = pool.slice(0, limit)

  return selected.map((word) => mapWordToQuestion(word, input.direction))
}

function mapWordToQuestion(word: Word, direction: WritingDirection): WritingQuestion {
  const showChinese = direction === 'zh' || direction === 'zh-pinyin'
  return {
    id: newId('wq'),
    type: 'vocabulary',
    direction,
    hskLevel: word.hsk_level,
    wordId: word.id,
    promptChinese: showChinese ? word.chinese : null,
    promptPinyin: direction === 'zh' ? null : word.pinyin,
    promptEnglish: direction === 'pinyin' || direction === 'zh' || direction === 'zh-pinyin' ? null : word.english,
    expectedAnswer: word.chinese,
    pinyin: word.pinyin,
    meaning: word.english,
    targetWords: [word.chinese],
  }
}

export interface SentenceStubInput {
  hskLevel: HSKLevel
  scope: WritingScope
  order: 'sequential' | 'random'
  questionCount: number
  version?: HSKVersion | null
}

/**
 * Sentence exercises are generated by AI, so we only pick the target words
 * up front and lazily fetch the actual sentence when the question is shown.
 */
export async function buildSentenceStubs(input: SentenceStubInput): Promise<WritingQuestion[]> {
  await ensureDb()
  const levels = new Set(levelsFor(input.scope, input.hskLevel))

  const all = await wordService.getAll(input.version ?? undefined)
  let pool = all.filter((w) => levels.has(w.hsk_level) && w.chinese.trim().length > 0)
  if (input.order === 'random') pool = shuffle(pool)

  const limit = input.questionCount > 0 ? input.questionCount : Math.min(pool.length, 20)
  const selected = pool.slice(0, limit)

  return selected.map((word) => ({
    id: newId('sq'),
    type: 'sentence',
    direction: 'sentence',
    hskLevel: word.hsk_level,
    wordId: word.id,
    promptChinese: null,
    promptPinyin: null,
    promptEnglish: null,
    expectedAnswer: '',
    pinyin: '',
    meaning: '',
    targetWords: [word.chinese],
  }))
}

/** Fill in a sentence stub with a validated AI sentence. */
export async function hydrateSentenceQuestion(
  question: WritingQuestion,
  difficulty: SentenceDifficulty,
): Promise<WritingQuestion> {
  const exercise = await getSentenceExercise({
    hskLevel: question.hskLevel,
    difficulty,
    targetWord: question.targetWords[0] ?? null,
  })

  return {
    ...question,
    promptChinese: null,
    promptPinyin: exercise.pinyin,
    promptEnglish: exercise.translation,
    expectedAnswer: exercise.sentence,
    pinyin: exercise.pinyin,
    meaning: exercise.translation,
    targetWords: exercise.targetWords.length > 0 ? exercise.targetWords : question.targetWords,
  }
}

// ── AI sentence generation (server-proxied) ────────────────────────────────

function sentenceCacheId(level: HSKLevel, difficulty: SentenceDifficulty, targetWord: string | null): string {
  return `${level}|${difficulty}|${targetWord || 'any'}`
}

function mapCachedSentence(row: any): SentenceExercise {
  return {
    sentence: row.sentence,
    pinyin: row.pinyin,
    translation: row.translation,
    targetWords: JSON.parse(row.target_words || '[]'),
    hskLevel: Number(row.hsk_level) as HSKLevel,
  }
}

export class SentenceGenerationError extends Error {
  code: string
  constructor(message: string, code = 'ai_error') {
    super(message)
    this.name = 'SentenceGenerationError'
    this.code = code
  }
}

export async function getSentenceExercise(params: {
  hskLevel: HSKLevel
  difficulty: SentenceDifficulty
  targetWord: string | null
}): Promise<SentenceExercise> {
  await ensureDb()
  const { hskLevel, difficulty, targetWord } = params
  const cacheId = sentenceCacheId(hskLevel, difficulty, targetWord)

  const cached = query('SELECT * FROM writing_sentence_cache WHERE id = ?', [cacheId])
  if (cached.length > 0) return mapCachedSentence(cached[0])

  const token = typeof localStorage !== 'undefined' ? getStoredToken() : null
  let response: Response
  try {
    response = await fetch('/api/writing/ai-sentence', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
      },
      body: JSON.stringify({ hskLevel, difficulty, targetWord }),
    })
  } catch {
    throw new SentenceGenerationError('Network problem — check your connection and try again.', 'network')
  }

  if (response.status === 429) {
    const retryAfter = response.headers.get('Retry-After')
    const suffix = retryAfter ? ` Try again in ${retryAfter}s.` : ''
    throw new SentenceGenerationError(`Daily sentence limit reached.${suffix}`, 'rate_limit')
  }

  if (!response.ok) {
    let message = 'The AI could not generate a sentence right now.'
    try {
      const body = await response.json()
      if (body?.error) message = String(body.error)
    } catch {
      // keep default message
    }
    throw new SentenceGenerationError(message, 'ai_error')
  }

  let data: any
  try {
    data = await response.json()
  } catch {
    throw new SentenceGenerationError('The AI returned an invalid response.', 'invalid')
  }

  const exercise = validateSentenceExercise(data, hskLevel)

  run(
    `INSERT OR REPLACE INTO writing_sentence_cache (id, hsk_level, difficulty, sentence, pinyin, translation, target_words, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      cacheId,
      hskLevel,
      difficulty,
      exercise.sentence,
      exercise.pinyin,
      exercise.translation,
      JSON.stringify(exercise.targetWords),
      new Date().toISOString(),
    ],
  )

  return exercise
}

function validateSentenceExercise(data: any, level: HSKLevel): SentenceExercise {
  const sentence = typeof data?.sentence === 'string' ? data.sentence.trim() : ''
  const pinyin = typeof data?.pinyin === 'string' ? data.pinyin.trim() : ''
  const translation = typeof data?.translation === 'string' ? data.translation.trim() : ''
  const targetWords = Array.isArray(data?.target_words)
    ? data.target_words.filter((w: unknown): w is string => typeof w === 'string')
    : []

  if (!sentence || !pinyin || !translation) {
    throw new SentenceGenerationError('The AI returned an incomplete sentence.', 'invalid')
  }
  if (!/[\u4e00-\u9fff]/.test(sentence)) {
    throw new SentenceGenerationError('The AI response was not Chinese.', 'invalid')
  }

  return { sentence, pinyin, translation, targetWords, hskLevel: level }
}

// ── Persistence ────────────────────────────────────────────────────────────

export const writingService = {
  async saveSession(session: WritingSessionRecord): Promise<void> {
    await ensureDb()
    run(
      `INSERT OR REPLACE INTO writing_sessions
        (id, user_id, hsk_level, scope, practice_mode, order_type, question_count, correct_count, accuracy, started_at, completed_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        session.id,
        session.user_id,
        session.hsk_level,
        session.scope,
        session.practice_mode,
        session.order_type,
        session.question_count,
        session.correct_count,
        session.accuracy,
        session.started_at,
        session.completed_at,
      ],
    )
  },

  async saveAttempt(attempt: WritingAttemptRecord): Promise<void> {
    await ensureDb()
    run(
      `INSERT OR REPLACE INTO writing_attempts
        (id, session_id, user_id, word_id, question_type, expected_answer, user_answer, pinyin_input, is_correct, accuracy, time_taken, mistakes, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        attempt.id,
        attempt.session_id,
        attempt.user_id,
        attempt.word_id,
        attempt.question_type,
        attempt.expected_answer,
        attempt.user_answer,
        attempt.pinyin_input,
        attempt.is_correct ? 1 : 0,
        attempt.accuracy,
        attempt.time_taken,
        attempt.mistakes,
        attempt.created_at,
      ],
    )
  },

  async getStats(userId: string): Promise<WritingStats> {
    await ensureDb()
    const rows = query(
      `SELECT COUNT(*) as sessions, COALESCE(SUM(question_count),0) as questions,
              COALESCE(SUM(correct_count),0) as correct, MAX(completed_at) as last
       FROM writing_sessions WHERE user_id = ?`,
      [userId],
    )
    const row = rows[0] || {}
    const sessions = Number(row.sessions || 0)
    const questions = Number(row.questions || 0)
    const correct = Number(row.correct || 0)
    return {
      sessions,
      questions,
      correct,
      accuracy: questions > 0 ? Math.round((correct / questions) * 100) : 0,
      lastPracticedAt: row.last || null,
    }
  },

  async getWeakWords(userId: string, limit = 8): Promise<WritingWeakWord[]> {
    await ensureDb()
    const rows = query(
      `SELECT expected_answer as label, COUNT(*) as attempts, COALESCE(SUM(is_correct),0) as correct
       FROM writing_attempts
       WHERE user_id = ?
       GROUP BY expected_answer
       ORDER BY (CAST(COALESCE(SUM(is_correct),0) AS REAL) / COUNT(*)) ASC, attempts DESC
       LIMIT ?`,
      [userId, limit],
    )
    return rows
      .map((r: any) => {
        const attempts = Number(r.attempts || 0)
        const correct = Number(r.correct || 0)
        return {
          label: String(r.label),
          attempts,
          correct,
          accuracy: attempts > 0 ? Math.round((correct / attempts) * 100) : 0,
        }
      })
      .filter((w: WritingWeakWord) => w.accuracy < 100 && w.label)
  },

  async getCharacterMistakes(userId: string, limit = 8): Promise<string[]> {
    await ensureDb()
    const rows = query(
      `SELECT mistakes FROM writing_attempts WHERE user_id = ? AND is_correct = 0 ORDER BY created_at DESC LIMIT 200`,
      [userId],
    )
    const counts = new Map<string, number>()
    for (const row of rows as any[]) {
      try {
        const chars: string[] = JSON.parse(row.mistakes || '[]')
        for (const char of chars) {
          if (!char) continue
          counts.set(char, (counts.get(char) || 0) + 1)
        }
      } catch {
        // ignore malformed rows
      }
    }
    return Array.from(counts.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(0, limit)
      .map(([char]) => char)
  },
}