// Chinese-English Dictionary for HSK 1-4 Vocabulary
// Maps Chinese characters/pinyin to English translations

const dict = {
  // ============ HSK 1 ============
  '爱': 'to love; love',
  '八': 'eight',
  '爸爸': 'father; dad',
  '杯子': 'cup; glass',
  '北京': 'Beijing',
  '本': 'book; volume; root; origin',
  '本子': 'notebook',
  '笔': 'pen; pencil',
  '不': 'not; no',
  '不客气': "you're welcome",
  '不要': "don't; must not",
  '菜': 'vegetable; dish; cuisine',
  '茶': 'tea',
  '车': 'car; vehicle',
  '车票': 'ticket (for bus/train)',
  '出租车': 'taxi',
  '车站': 'station; stop',
  '吃': 'to eat',
  '出': 'to go out; to exit',
  '出去': 'to go out',
  '穿': 'to wear; to put on',
  '床': 'bed',
  '打电话': 'to make a phone call',
  '大': 'big; large',
  '的': 'possessive particle; of',
  '到': 'to arrive; to reach',
  '得': 'structural particle; have to',
  '等': 'to wait; etc.',
  '弟弟': 'younger brother',
  '地方': 'place; location',
  '点': 'point; dot; o\'clock',
  '电脑': 'computer',
  '电视': 'television',
  '电影': 'movie; film',
  '东西': 'thing; stuff',
  '都': 'all; both',
  '读': 'to read',
  '对': 'correct; toward',
  '对不起': 'sorry; excuse me',
  '多': 'many; much; how...',
  '多少': 'how many; how much',
  '二': 'two',
  '饭店': 'restaurant; hotel',
  '房子': 'house; building',
  '飞机': 'airplane',
  '分钟': 'minute',
  '服务员': 'waiter; attendant',
  '高兴': 'happy; glad',
  '告诉': 'to tell',
  '哥哥': 'older brother',
  '歌': 'song',
  '个': 'general measure word',
  '给': 'to give; for',
  '关': 'to close; to turn off',
  '国': 'country; nation',
  '国家': 'country; nation',
  '汉语': 'Chinese language',
  '汉字': 'Chinese character',
  '好': 'good; well',
  '号': 'number; date',
  '喝': 'to drink',
  '和': 'and; with',
  '很': 'very',
  '后面': 'behind; back',
  '会': 'can; will; meeting',
  '回': 'to return; to go back',
  '回答': 'to answer; reply',
  '回来': 'to come back',
  '回去': 'to go back',
  '火': 'fire',
  '火车站': 'train station',
  '机场': 'airport',
  '家': 'home; family',
  '叫': 'to call; to be called',
  '姐姐': 'older sister',
  '介绍': 'to introduce; introduction',
  '今天': 'today',
  '进': 'to enter; to go in',
  '进来': 'to come in',
  '进去': 'to go in',
  '九': 'nine',
  '就': 'just; then; exactly',
  '觉得': 'to feel; to think',
  '开': 'to open; to start',
  '看': 'to see; to look; to watch',
  '看见': 'to see; to catch sight of',
  '考试': 'exam; test',
  '渴': 'thirsty',
  '课': 'class; lesson',
  '来': 'to come',
  '来自': 'to come from',
  '老师': 'teacher',
  '了': 'completed action particle',
  '里': 'inside; in',
  '六': 'six',
  '冷': 'cold',
  '买': 'to buy',
  '忙': 'busy',
  '没有': "don't have; haven't",
  '没关系': "it doesn't matter",
  '妹妹': 'younger sister',
  '门口': 'doorway; entrance',
  '面': 'face; side; noodles',
  '面条': 'noodles',
  '明天': 'tomorrow',
  '名字': 'name',
  '拿': 'to take; to hold',
  '哪': 'which; where',
  '哪儿': 'where',
  '哪里': 'where',
  '那': 'that; then',
  '那儿': 'there',
  '那里': 'there',
  '奶奶': 'grandmother (paternal)',
  '男': 'male; man',
  '男人': 'man',
  '难': 'difficult; hard',
  '呢': 'modal particle',
  '能': 'can; be able to',
  '你': 'you',
  '你们': 'you (plural)',
  '年': 'year',
  '女': 'female; woman',
  '女儿': 'daughter',
  '女人': 'woman',
  '跑步': 'to run; jogging',
  '朋友': 'friend',
  '漂亮': 'beautiful; pretty',
  '苹果': 'apple',
  '七': 'seven',
  '钱': 'money',
  '前面': 'front; ahead',
  '请': 'please; to invite',
  '请问': 'excuse me; may I ask',
  '去': 'to go',
  '热': 'hot',
  '人': 'person; people',
  '认识': 'to know; to recognize',
  '容易': 'easy',
  '三': 'three',
  '商店': 'shop; store',
  '上班': 'to go to work',
  '上': 'on; above; to go up',
  '上午': 'morning; before noon',
  '上学': 'to go to school',
  '少': 'few; little; less',
  '生病': 'to fall ill',
  '什么': 'what',
  '时候': 'time; moment',
  '十': 'ten',
  '是': 'to be; is; am; are',
  '手': 'hand',
  '手机': 'cell phone',
  '书': 'book',
  '蔬菜': 'vegetables',
  '水': 'water',
  '水果': 'fruit',
  '睡': 'to sleep',
  '睡觉': 'to sleep; to go to bed',
  '说': 'to say; to speak',
  '说话': 'to talk; to speak',
  '死': 'to die; death',
  '四': 'four',
  '虽然': 'although; though',
  '他': 'he; him',
  '他们': 'they; them',
  '她': 'she; her',
  '她们': 'they; them (female)',
  '太': 'too; very',
  '天气': 'weather',
  '听': 'to listen; to hear',
  '同学': 'classmate',
  '图书馆': 'library',
  '外国': 'foreign country',
  '外国人': 'foreigner',
  '完': 'to finish; complete',
  '玩': 'to play; to have fun',
  '晚上': 'evening; night',
  '喂': 'hello (on phone); hey',
  '问题': 'question; problem',
  '我': 'I; me',
  '我们': 'we; us',
  '五': 'five',
  '下课': 'class is over',
  '下': 'down; below; next',
  '下午': 'afternoon',
  '下雨': 'to rain',
  '现': 'now; appear',
  '现在': 'now; at present',
  '想': 'to think; to want; to miss',
  '小': 'small; little',
  '小孩': 'child; kid',
  '小学生': 'elementary school student',
  '写': 'to write',
  '谢谢': 'thank you',
  '新': 'new',
  '星期': 'week',
  '星期二': 'Tuesday',
  '星期六': 'Saturday',
  '星期日': 'Sunday',
  '星期三': 'Wednesday',
  '星期四': 'Thursday',
  '星期五': 'Friday',
  '星期一': 'Monday',
  '星星': 'star',
  '学': 'to learn; to study',
  '学生': 'student',
  '学校': 'school',
  '也': 'also; too',
  '要': 'to want; to need; will',
  '药': 'medicine; drug',
  '爷爷': 'grandfather (paternal)',
  '一': 'one',
  '一点儿': 'a little; a bit',
  '衣服': 'clothes; clothing',
  '医生': 'doctor',
  '医院': 'hospital',
  '以后': 'later; after',
  '以前': 'before; previously',
  '椅子': 'chair',
  '因为': 'because',
  '音乐': 'music',
  '影响': 'to influence; influence',
  '游泳': 'to swim; swimming',
  '有': 'to have; there is/are',
  '有名': 'famous',
  '又': 'again; also',
  '右边': 'right side',
  '雨': 'rain',
  '月': 'month; moon',
  '月亮': 'moon',
  '在': 'at; in; on; to be at',
  '再见': 'goodbye',
  '怎么': 'how; why',
  '怎么样': 'how about; how',
  '找': 'to look for; to find',
  '这': 'this',
  '这儿': 'here',
  '这里': 'here',
  '真': 'really; truly',
  '正在': 'in the process of',
  '知道': 'to know; to be aware',
  '住': 'to live; to reside',
  '准备': 'to prepare; preparation',
  '走吧': "let's go",
  '走路': 'to walk',
  '粽子': 'zongzi (rice dumpling)',
  '坐': 'to sit; to take (transport)',
  '做饭': 'to cook',
  '做': 'to do; to make',
  '啊': 'ah; oh (interjection)',
  '白': 'white',
  '百': 'hundred',
  '班': 'class; team; shift',
  '半': 'half',
  '帮忙': 'to help; help',
  '包子': 'steamed stuffed bun',
  '报': 'newspaper; to report',
  '报纸': 'newspaper',
  '比': 'to compare; than',
  '别': "don't; other",
  '别人': 'other people; others',
  '打': 'to hit; to play; to make',
  '打开': 'to open; to turn on',
  '大学': 'university; college',
  '当然': 'of course',
  '蛋': 'egg',
  '蛋糕': 'cake',
  '但是': 'but; however',
  '低': 'low',
  '第一次': 'first time',
  '电梯': 'elevator',
  '店': 'shop; store',
  '短': 'short',
  '锻炼': 'to exercise; workout',
  '饿': 'hungry',
  '发烧': 'to have a fever',
  '发现': 'to discover; to find',
  '方便': 'convenient',
  '饭馆': 'restaurant',
  '放': 'to put; to place; to release',
  '放假': 'to have a holiday/vacation',
  '父母': 'parents',
  '父亲': 'father',
  '干净的': 'clean',
  '干吗': 'what for; why',
  '感谢': 'to thank; gratitude',
  '干': 'dry; to do',
  '高': 'tall; high',
  '更': 'more; even more',
  '公交车': 'public bus',
  '公共': 'public',
  '公园': 'park',
  '刮风': 'windy; to blow (wind)',
  '挂': 'to hang; to hang up',
  '贵': 'expensive; precious',
  '过': 'to cross; past; experiential particle',
  '过来': 'to come over',
  '过去': 'past; to go over; to pass',
  '还': 'still; yet; also',
  '还是': 'still; or',
  '孩子': 'child; children',
  '好吃': 'delicious; tasty',
  '黑': 'black; dark',
  '红': 'red',
  '画': 'to draw; painting; picture',
  '坏': 'bad; broken',
  '欢迎': 'to welcome; welcome',
  '换': 'to change; to exchange',
  '黄色': 'yellow',
  '急': 'urgent; anxious; hurried',
  '几': 'how many; several',
  '记': 'to remember; to record',
  '见面': 'to meet; meeting',
  '件': 'measure word for items/clothes',
  '健康': 'healthy; health',
  '教': 'to teach',
  '教室': 'classroom',
  '接': 'to receive; to pick up; to connect',
  '节日': 'festival; holiday',
  '结束': 'to end; to finish',
  '讲话': 'to speak; speech',
  '近': 'near; close',
  '经常': 'often; frequently',
  '经过': 'to pass through; to go by',
  '久': 'long (time)',
  '开始': 'to start; to begin',
  '开心': 'happy; delighted',
  '可能': 'possible; maybe',
  '可以': 'can; may; OK',
  '快': 'fast; quick; soon',
  '快乐': 'happy; joyful',
  '筷子': 'chopsticks',
  '块': 'piece; lump; yuan (money)',
  '累': 'tired; exhausted',
  '练习': 'to practice; exercise',
  '了解': 'to understand; to know about',
  '零': 'zero',
  '路': 'road; path; way',
  '妈妈': 'mother; mom',
  '马上': 'immediately; right away',
  '慢': 'slow',
  '米饭': 'cooked rice',
  '母': 'mother; female',
  '母亲': 'mother',
  '牛奶': 'milk',
  '努力': 'to work hard; effort',
  '瓶': 'bottle',
  '瓶盖': 'bottle cap',
  '其实': 'actually; in fact',
  '骑': 'to ride (bike, horse)',
  '起来': 'to get up; to rise; to start',
  '千': 'thousand',
  '秋': 'autumn; fall',
  '让': 'to let; to allow; to make',
  '然后': 'then; after that',
  '热闹': 'lively; bustling',
  '身体': 'body; health',
  '生日': 'birthday',
  '时间': 'time',
  '事情': 'thing; matter; affair',
  '虽然~': 'although~',
  '所以': 'so; therefore',
  '太~了': 'too ~ (very)',
  '疼': 'painful; to hurt',
  '踢': 'to kick; to play (football)',
  '体育': 'sports; physical education',
  '天': 'day; sky; heaven',
  '跳': 'to jump; to dance',
  '跳舞': 'to dance',
  '听说': 'to hear of; to be told',
  '外': 'outside; outer',
  '外面': 'outside',
  '完饭': '(see 做饭)',
  '网球': 'tennis',
  '忘': 'to forget',
  '为什么': 'why',
  '文章': 'article; essay',
  '问': 'to ask',
  '希望': 'to hope; hope; wish',
  '习惯': 'habit; custom; to be used to',
  '喜欢': 'to like; to love',
  '先生': 'Mr.; sir; husband',
  '小时': 'hour',
  '笑': 'to laugh; to smile',
  '些': 'some; a few',
  '鞋': 'shoe',
  '休息': 'to rest',
  '选': 'to choose; to select',
  '颜色': 'color',
  '眼': 'eye',
  '眼睛': 'eye',
  '药片': 'tablet; pill',
  '一定': 'certainly; definitely',
  '一共': 'in total; altogether',
  '一起': 'together',
  '一直': 'always; all along',
  '已经': 'already',
  '意思': 'meaning; idea',
  '应该': 'should; ought to',
  '用': 'to use',
  '远': 'far; distant',
  '早': 'early; morning',
  '早上': 'early morning',
  '站': 'to stand; station; stop',
  '长': 'long; to grow',
  '张': 'measure word for flat objects',
  '着急': 'anxious; worried',
  '真正': 'real; true; genuine',
  '只': 'only; just',
  '中国': 'China',
  '中文': 'Chinese language',
  '中间': 'middle; center',
  '钟': 'clock; bell',
  '重要': 'important',
  '周末': 'weekend',
  '主要': 'main; primary',
  '桌子': 'table; desk',
  '字': 'character; word; letter',
  '字典': 'dictionary',
  '自己': 'oneself; self',
  '自行车': 'bicycle',
  '总是': 'always',
  '走': 'to walk; to go; to leave',
  '最': 'most; -est',
  '最后': 'final; last; finally',
  '最近': 'recently; lately',
  '昨天': 'yesterday',
  '左边': 'left side',
  '作业': 'homework; assignment',

  // ============ HSK 2 continued ============,
  '爱好': 'hobby; interest',
  '白色': 'white color',
  '帮助': 'to help; assistance',
  '包': 'bag; package; to wrap',
  '报名': 'to register; to sign up',
  '比赛': 'competition; match; to compete',
  '必须': 'must; have to',
  '变': 'to change; to become',
  '变成': 'to change into; to become',
  '变化': 'change; variation',
  '表演': 'to perform; performance',
  '不但': 'not only',
  '不过': 'but; however; only',
  '不同': 'different; not the same',
  '不要了': "don't want anymore",
  '部分': 'part; section; portion',
  '参加': 'to participate; to join',
  '参观': 'to visit; to tour',
  '草': 'grass',
  '长大小': 'to grow up',
  '唱歌': 'to sing',
  '城市': 'city',
  '出现': 'to appear; to emerge',
  '除非': 'unless',
  '旁边': 'beside; next to',
  '成为': 'to become',
  '吃药': 'to take medicine',
  '除了': 'except; besides; in addition to',
  '窗户': 'window',
  '春节': 'Spring Festival (Chinese New Year)',
  '吹': 'to blow',
  '春节前': 'before Spring Festival',
  '从': 'from; since',
  '从来': 'always; ever; never',
  '从前': 'before; in the past',
  '错': 'wrong; mistaken; error',
  '答案': 'answer; solution',
  '大声': 'loudly; loud',
  '带': 'to bring; to take; to carry',
  '担心': 'to worry; worried',
  '倒': 'to fall; to pour; inverted',
  '得到': 'to get; to obtain',
  '灯': 'lamp; light',
  '第一': 'first; number one',
  '分': 'minute; cent; to divide',
  '丰富': 'rich; abundant; plentiful',
  '否则': 'otherwise; else',
  '服务员~': '(see 服务员)',
  '改变': 'to change; to alter',
  '敢': 'to dare; bold',
  '感到': 'to feel; to sense',
  '感兴趣': 'to be interested in',
  '干活儿': 'to work; to do work',
  '个子': 'height; stature',
  '功课': 'schoolwork; homework; lessons',
  '够': 'enough; sufficient',
  '关照': 'to look after; to take care of',
  '广播': 'broadcast; to broadcast',
  '广告': 'advertisement; ad',
  '国家~': '(see 国家)',
  '海边': 'seaside; beach',
  '行': 'OK; all right; row; profession',
  '好像': 'seems; as if; like',
  '号~': '(see 号)',
  '合影': 'group photo',
  '河': 'river',
  '湖': 'lake',
  '护照': 'passport',
  '花': 'flower; to spend (money/time)',
  '花园': 'garden',
  '化学': 'chemistry',
  '环境': 'environment; surroundings',
  '或者': 'or; either',
  '几乎': 'almost; nearly',
  '机会': 'opportunity; chance',
  '极': 'extremely; pole',
  '计划': 'plan; to plan',
  '记住': 'to remember; to memorize',
  '简单': 'simple; easy',
  '建设': 'to build; to construct',
  '建议': 'suggestion; to suggest',
  '将来': 'future; in the future',
  '讲': 'to speak; to tell; to explain',
  '交流': 'to communicate; to exchange',
  '交通': 'traffic; transportation',
  '饺子': 'dumpling',
  '教育': 'education; to educate',
  '解决': 'to solve; to resolve',
  '进步': 'progress; improvement',
  '经常~': '(see 经常)',
  '经济': 'economy; economic',
  '经验': 'experience',
  '决定': 'to decide; decision',
  '科学': 'science',
  '咳嗽': 'to cough; cough',
  '空气': 'air; atmosphere',
  '口': 'mouth; opening; measure word',
  '哭': 'to cry; to weep',
  '困难': 'difficult; difficulty; hardship',
  '浪费': 'to waste; wasteful',
  '离开': 'to leave; to depart',
  '历史': 'history',
  '脸': 'face',
  '联系': 'to contact; connection',
  '凉': 'cool; cold',
  '两个': 'both; two (items)',
  '聊天儿': 'to chat; to talk',
  '邻居': 'neighbor',
  '留学': 'to study abroad',
  '旅游': 'to travel; tourism',
  '绿化': 'greening; afforestation',
  '绿色': 'green (color)',
  '麻烦': 'troublesome; trouble; to bother',
  '猫': 'cat',
  '毛巾': 'towel',
  '毛衣': 'sweater',
  '帽子': 'hat; cap',
  '美丽': 'beautiful',
  '米': 'rice (uncooked); meter',
  '民族': 'ethnic group; nation; nationality',
  '明白': 'to understand; clear',
  '目前': 'currently; at present',
  '拿手': 'to be good at; specialty',
  '内容': 'content; substance',
  '能力': 'ability; capability',
  '年级': 'grade; year (in school)',
  '鸟': 'bird',
  '暖和': 'warm (weather)',
  '爬山': 'to climb a mountain',
  '排球': 'volleyball',
  '盘子': 'plate; dish',
  '胖': 'fat; plump',
  '啤酒': 'beer',
  '骗': 'to deceive; to cheat',
  '平时': 'usually; normally; in normal times',
  '葡萄': 'grape',
  '普通': 'ordinary; common; general',
  '普通话': 'Mandarin Chinese',
  '其次': 'next; secondly',
  '其中': 'among; in which',
  '其他': 'other; else',
  '汽车': 'car; automobile',
  '铅笔': 'pencil',
  '晴天': 'sunny day; clear weather',
  '清楚': 'clear; to understand clearly',
  '请假': 'to ask for leave',
  '请假条': 'leave request note',
  '请进': 'please come in',
  '请客': 'to treat (someone to a meal)',
  '秋千': 'swing (playground)',
  '全部': 'all; entire; whole',
  '缺乏': 'to lack; shortage',
  '却': 'but; yet; however',
  '确定': 'to confirm; definite; certain',
  '然后~': '(see 然后)',
  '认真': 'serious; earnest; conscientious',
  '任务': 'task; mission; assignment',
  '仍然': 'still; yet; as before',
  '如果': 'if; in case',
  '散步': 'to take a walk',
  '沙发': 'sofa; couch',
  '社会': 'society',
  '甚至': 'even; so much so that',
  '生动': 'vivid; lively',
  '生活': 'life; livelihood; to live',
  '生气': 'to get angry; angry',
  '省': 'to save; to economize; province',
  '十分': 'very; extremely; fully',
  '使': 'to make; to cause; to use',
  '世纪': 'century',
  '世界': 'world',
  '是否': 'whether or not; if',
  '适合': 'to suit; to fit; suitable',
  '收费': 'to charge; fee',
  '收入': 'income; revenue',
  '收拾': 'to tidy up; to put in order',
  '首都': 'capital (city)',
  '首先': 'first; first of all; above all',
  '受不了': "can't stand; unbearable",
  '受伤': 'to be injured; injury',
  '输入': 'to input; to import',
  '暑假': 'summer vacation',
  '树林': 'woods; forest; grove',
  '帅': 'handsome; good-looking',
  '顺利': 'smooth; successful; without a hitch',
  '顺序': 'order; sequence',
  '说明': 'to explain; explanation',
  '思想': 'thought; thinking; ideology',
  '速度': 'speed; rate; velocity',
  '塑料袋': 'plastic bag',
  '塑料袋~': '(see 塑料袋)',
  '算': 'to calculate; to count as; to consider',
  '随便': 'casual; random; as one pleases',
  '随着': 'along with; following; as',
  '所有': 'all; every',
  '台': 'platform; stage; measure word',
  '太阳': 'sun; sunshine',
  '弹': 'to play (instrument); to pluck',
  '汤': 'soup; broth',
  '躺': 'to lie down',
  '趟': 'measure word for trips/times',
  '特点': 'characteristic; feature',
  '提供': 'to provide; to supply; to offer',
  '提前': 'in advance; ahead of time',
  '提醒': 'to remind; to warn',
  '体检': 'physical examination; health check',
  '体温': 'body temperature',
  '条件': 'condition; requirement; terms',
  '通过': 'to pass; to go through; by means of',
  '通知': 'to notify; notice; notification',
  '童年': 'childhood',
  '同时': 'at the same time; simultaneously',
  '同意': 'to agree; agreement',
  '突然': 'sudden; suddenly; unexpected',
  '团结': 'to unite; unity; solidarity',
  '推迟': 'to postpone; to put off',
  '推出': 'to launch; to release; to push out',
  '脱': 'to take off (clothes); to escape',
  '袜子': 'socks; stockings',
  '外国~': '(see 外国)',
  '完成': 'to complete; to finish; to accomplish',
  '完全': 'complete; completely; entirely',
  '微信': 'WeChat',
  '位置': 'position; location; place',
  '文章~': '(see 文章)',
  '无论': 'no matter; regardless of',
  '吸烟': 'to smoke; smoking',
  '希望~': '(see 希望)',
  '洗澡': 'to take a bath; to shower',
  '现代': 'modern; contemporary',
  '相当': 'quite; fairly; rather',
  '相信': 'to believe; to trust',
  '箱子': 'box; suitcase; trunk',
  '相反': 'opposite; contrary',
  '相同': 'same; identical',
  '香': 'fragrant; savory; delicious',
  '响': 'to sound; to make a sound; loud',
  '消息': 'news; information; message',
  '小吃': 'snack; refreshments',
  '小伙子': 'young man; lad',
  '小说': 'novel; fiction',
  '笑话': 'joke; to laugh at',
  '信封': 'envelope',
  '信息': 'information; news; message',
  '信心': 'confidence; faith',
  '兴奋': 'excited; excitement',
  '行~': '(see 行)',
  '幸运': 'lucky; fortunate; luck',
  '需要': 'to need; requirement; need',
  '选择': 'to choose; to select; choice',
  '学生~': '(see 学生)',
  '学期': 'semester; school term',
  '压力': 'pressure; stress',
  '牙膏': 'toothpaste',
  '亚洲': 'Asia',
  '严重': 'serious; severe; grave',
  '研究生': 'graduate student; postgraduate',
  '演出': 'to perform; performance; show',
  '演员': 'actor; performer',
  '阳光': 'sunlight; sunshine',
  '样子': 'appearance; manner; pattern',
  '邀请': 'to invite; invitation',
  '要是': 'if; in case; suppose',
  '钥匙': 'key',
  '也许': 'perhaps; maybe; probably',
  '叶子': 'leaf',
  '一切': 'everything; all',
  '一样': 'same; alike; as...as',
  '以为': 'to think (mistakenly); to assume',
  '意见': 'opinion; suggestion; objection',
  '意思~': '(see 意思)',
  '因此': 'therefore; consequently; thus',
  '引起': 'to cause; to give rise to; to lead to',
  '印象': 'impression',
  '赢': 'to win; to beat',
  '勇敢': 'brave; courageous',
  '永远': 'forever; always; eternal',
  '优点': 'advantage; merit; strong point',
  '优美': 'graceful; beautiful; elegant',
  '尤其': 'especially; particularly',
  '由': 'by; from; due to',
  '由于': 'due to; because of; owing to',
  '友好': 'friendly; amicable',
  '友谊': 'friendship',
  '有趣': 'interesting; fun; amusing',
  '有效': 'effective; valid',
  '于是': 'therefore; then; consequently',
  '语法': 'grammar',
  '预习': 'to preview; to prepare lessons',

  // ============ HSK 3 partial ============,
  '阿姨': 'aunt; auntie; Mrs. (for older women)',
  '安静': 'quiet; calm; peaceful',
  '安全': 'safe; secure; safety',
  '把': 'to hold; marker for object; measure word',
  '班长': 'class monitor; squad leader',
  '办法': 'method; way; means',
  '办公室': 'office',
  '半夜': 'midnight; in the middle of the night',
  '保护': 'to protect; protection',
  '保证': 'to guarantee; to assure; guarantee',
  '报道': 'to report (news); news report',
  '北方': 'north; northern region',
  '背后': 'behind; at the back; behind the scenes',
  '本来': 'originally; at first; it goes without saying',
  '比较': 'to compare; relatively; quite',
  '毕竟': 'after all; in the final analysis',
  '避免': 'to avoid; to prevent; to refrain from',
  '遍': 'measure word for times; all over',
  '表达': 'to express; expression',
  '表面': 'surface; appearance; outward',
  '表示': 'to express; to show; to indicate',
  '表演~': '(see 表演)',
  '表扬': 'to praise; to commend',
  '饼干': 'biscuit; cookie; cracker',
  '并且': 'and; besides; moreover; furthermore',
  '博士': 'doctor (Ph.D.); doctoral degree',
  '博物馆': 'museum',
  '补充': 'to supplement; to add; supplement',
  '不好意思': 'embarrassed; sorry; feel shy',
  '不久': 'soon; before long; not long',
  '不论': 'no matter; regardless of; whether',
  '不少': 'quite a few; many; not a few',
  '不一定': 'not necessarily; not sure',
  '不住': 'continuously; cannot stop',
  '布置': 'to arrange; to decorate; to assign',
  '部门': 'department; division; section',
  '部队': 'army; troops; forces',
  '材料': 'material; data; stuff',
  '财产': 'property; wealth; assets',
  '采访': 'to interview; to gather news',
  '采取': 'to adopt; to take; to carry out',
  '餐厅': 'dining hall; restaurant; cafeteria',
  '产生': 'to produce; to generate; to arise',
  '超过': 'to exceed; to surpass; to overtake',
  '炒': 'to stir-fry; to fry',
  '成语': 'idiom; set phrase',
  '成立': 'to establish; to set up; to found',
  '成为~': '(see 成为)',
  '成长': 'to grow up; growth; development',
  '虫子': 'insect; bug; worm',
  '重新': 'again; anew; re-',
  '抽烟': 'to smoke (cigarette)',
  '出口': 'exit; to export',
  '出生': 'to be born; birth',
  '出席': 'to attend; to be present',
  '厨房': 'kitchen',
  '除非~': '(see 除非)',
  '处理': 'to handle; to deal with; to process',
  '传真': 'fax; facsimile',
  '窗户~': '(see 窗户)',
  '创造': 'to create; to produce; creation',
  '辞职': 'to resign; to quit a job',
  '存': 'to save; to deposit; to store',
  '错误': 'mistake; error; wrong',
  '达到': 'to reach; to achieve; to attain',
  '打扮': 'to dress up; to make up; to decorate',
  '打印': 'to print',
  '打招呼': 'to greet; to say hello; to notify',
  '大部分': 'most; the greater part; majority',
  '大量': 'large amount; great quantity; massive',
  '大象': 'elephant',
  '大约': 'approximately; about; roughly',
  '代表': 'to represent; representative; on behalf of',
  '代替': 'to replace; to substitute',
  '待遇': 'treatment; pay; benefits',
  '单位': 'unit; organization; workplace',
  '蛋糕~': '(see 蛋糕)',
  '当地': 'local; in the locality',
  '当做': 'to treat as; to regard as; to take as',
  '岛': 'island',
  '导演': 'director (film/TV); to direct',
  '到达': 'to arrive; to reach',
  '到底': 'in the end; after all; on earth',
  '道德': 'morality; ethics; moral',
  '道理': 'reason; principle; truth; way',
  '登记': 'to register; to check in',
  '等于是': 'equivalent to; tantamount to',
  '地理': 'geography',
  '地球': 'the Earth; globe',
  '地位': 'position; status; standing',
  '地震': 'earthquake',
  '调查': 'to investigate; investigation; survey',
  '掉': 'to fall; to drop; to lose',
  '东': 'east',
  '东西~': '(see 东西)',
  '动作': 'movement; motion; action',
  '动物': 'animal',
  '肚子': 'belly; abdomen; stomach',
  '对待': 'to treat; to handle; treatment',
  '对方': 'the other side; counterpart',
  '对付': 'to deal with; to cope with; to handle',
  '多么': 'how; what; so',
  '儿童': 'children',
  '发表': 'to publish; to issue; to express',
  '发展': 'to develop; development; growth',
  '法律': 'law; legal',
  '反对': 'to oppose; to be against',
  '反复': 'repeatedly; over and over; reversal',
  '反应': 'to react; reaction; response',
  '反映': 'to reflect; to mirror; to report',
  '范围': 'range; scope; extent',
  '方法': 'method; way; means',
  '房间': 'room',
  '方式': 'way; manner; style; mode',
  '防止': 'to prevent; to guard against; to avoid',
  '访问': 'to visit; to access; visit',
  '仿佛': 'as if; seem; be like; similar',
  '放弃': 'to give up; to abandon; to renounce',
  '放心': 'to feel relieved; to be at ease',
  '非常': 'very; extremely; highly',
  '飞机~': '(see 飞机)',
  '费用': 'cost; expense; fee',
  '分钟/~': 'minute; see',
  '份': 'measure word; portion; share; copy',
  '奋斗': 'to struggle; to strive; to fight',
  '风格': 'style; manner; mode',
  '风景': 'scenery; landscape',
  '风险': 'risk; danger; hazard',
  '否定': 'to deny; to negate; negative',
  '符合': 'to conform; to accord with; to fit',
  '服装': 'clothing; dress; costume',
  '负担': 'burden; to bear; to shoulder',
  '复制': 'to copy; to duplicate; to reproduce',
  '该': 'should; ought; that; the said',
  '改正': 'to correct; to amend; to rectify',
  '概括': 'to summarize; to generalize; summary',
  '概念': 'concept; notion; idea',
  '感情': 'feeling; emotion; affection',
  '感受': 'to feel; to experience; feeling',
  '岗位': 'post; position; station',
  '高级': 'senior; high-level; advanced; high-grade',
  '高速公路': 'highway; expressway; freeway',
  '搞': 'to do; to make; to engage in',
  '告别': 'to say goodbye; to bid farewell',
  '胳膊': 'arm',
  '革命': 'revolution',
  '个人': 'individual; personal',
  '根本': 'fundamental; basic; at all; simply',
  '更加': 'even more; still more; further',
  '工厂': 'factory; plant; mill',
  '工程师': 'engineer',
  '工资': 'wages; salary; pay',
  '功夫': 'kung fu; skill; effort; time',
  '功能': 'function; functionality; feature',
  '共同': 'common; shared; together; jointly',
  '贡献': 'to contribute; contribution; dedication',
  '沟通': 'to communicate; communication',
  '构成': 'to constitute; to form; to make up',
  '孤独': 'lonely; solitary; alone',
  '古代': 'ancient times; antiquity',
  '古典': 'classical',
  '骨头': 'bone',
  '鼓励': 'to encourage; encouragement',
  '鼓舞': 'to inspire; to encourage; inspiration',
  '观众': 'audience; spectators; viewers',
  '关键': 'key; crucial; critical; key point',
  '观点': 'viewpoint; point of view; opinion',
  '观念': 'notion; concept; idea; sense',
  '管': 'to manage; to control; tube; pipe',
  '管理': 'to manage; management; administration',
  '光': 'light; ray; brightness; only; bare',
  '广播~': '(see 广播)',
  '广告~': '(see 广告)',
  '逛': 'to stroll; to roam; to wander',
  '规定': 'regulation; rule; to stipulate; to provide',
  '国籍': 'nationality; citizenship',
  '国际': 'international',
  '果汁': 'fruit juice',
  '过程': 'process; course; procedure',
  '海洋': 'ocean; sea',
  '害羞': 'shy; bashful; embarrassed',
  '寒假': 'winter vacation',
  '寒冷': 'cold; frigid; freezing',
  '喊': 'to shout; to call; to yell',
  '汗水': 'sweat; perspiration',
  '航班': 'flight; scheduled flight',
  '好处': 'benefit; advantage; good point',
  '好好': 'properly; well; carefully',
  '好笑': 'funny; amusing; laughable',
  '合格': 'qualified; up to standard',
  '盒子': 'box; case; container',
  '红包': 'red envelope (money gift)',
  '厚': 'thick; deep; generous',
  '后悔': 'to regret; remorse; repentance',
  '忽然': 'suddenly; all of a sudden',
  '互联网': 'Internet',
  '护士': 'nurse',
  '互相': 'mutually; each other; one another',
  '话剧': 'stage play; drama; modern drama',
  '怀疑': 'to doubt; to suspect; suspicion',
  '坏处': 'disadvantage; harm; downside',
  '环保': 'environmental protection',
  '换乘': 'to transfer; to change (transport)',
  '恢复': 'to recover; to restore; to resume',
  '回信': 'to reply to a letter; reply',
  '回忆': 'to recall; to recollect; memory',
  '会员': 'member; membership',
  '活': 'to live; alive; lively; work; job',
  '活动': 'activity; event; to move about',
  '活泼': 'lively; vivacious; active',
  '火~': '(see 火)',
  '货': 'goods; merchandise; cargo',
  '获得': 'to obtain; to gain; to acquire',
  '获奖': 'to win a prize/award',
  '获取': 'to obtain; to acquire; to get',
  '基本': 'basic; fundamental; basically',
  '基本上': 'basically; on the whole; generally',
  '基础': 'foundation; basis; base; basic',
  '激动': 'excited; emotional; to excite',
  '积极': 'positive; active; enthusiastic',
  '积累': 'to accumulate; accumulation',
  '及时': 'timely; in time; promptly',
  '即使': 'even if; even though',
  '既': 'both; since; already',
  '寄': 'to mail; to send; to post',
  '计划~': '(see 计划)',
  '既然': 'since; now that; as',
  '技术': 'technology; technique; skill',
  '继续': 'to continue; to go on; to proceed',
  '记者': 'journalist; reporter; correspondent',
  '加班': 'to work overtime',
  '家具': 'furniture',
  '加快': 'to speed up; to accelerate',
  '加强': 'to strengthen; to enhance; to reinforce',
  '加入': 'to join; to add; to participate',
  '加上': 'plus; in addition; to add',
  '家庭': 'family; household',
  '家乡': 'hometown; native place',
  '加油': 'to refuel; to cheer on; come on!',
  '加油站': 'gas station; filling station',
  '家长': 'parent; guardian; head of family',
  '假': 'fake; false; artificial; holiday',
  '价格': 'price; value',
  '价钱': 'price; cost',
  '假日': 'holiday; day off',
  '减': 'to reduce; to subtract; to decrease',
  '减轻': 'to lighten; to ease; to alleviate',
  '减少': 'to reduce; to decrease; to cut down',
  '健身': 'to work out; fitness; bodybuilding',
  '健身房': 'gym; fitness center',
  '建议~': '(see 建议)',
  '江': 'river (especially large ones)',
  '将': 'will; shall; to be going to; marker for object',
  '将来': '(already covered)',
  '将要': 'will; shall; be going to',
  '奖': 'prize; award; reward; to praise',
  '奖金': 'bonus; prize money; reward',
  '奖学金': 'scholarship',
  '降': 'to fall; to drop; to lower; to descend',
  '降低': 'to reduce; to lower; to cut down',
  '降价': 'to reduce price; price cut',
  '降落': 'to land; to descend; to drop',
  '降温': 'to cool down; temperature drop',
  '交': 'to hand over; to deliver; to associate',
  '骄傲': 'proud; arrogant; pride',
  '交警': 'traffic police',
  '交流~': '(see 交流)',
  '郊区': 'suburb; outskirts; suburban area',
  '交通~': '(see 交通)',
  '教练': 'coach; instructor; trainer',
  '教师': 'teacher; instructor',
  '教授': 'professor; to teach; to instruct',
  '教学': 'teaching; education; instruction',
  '教育~': '(see 教育)',
  '叫作': 'to be called; to be named',
  '街道': 'street; neighborhood; subdistrict',
  '接受': 'to accept; to receive; to take',
  '接着': 'next; then; to follow; to continue',
  '结果': 'result; outcome; as a result',
  '节': 'holiday; festival; section; joint; measure word',
  '节假日': 'holidays and festivals',
  '节约': 'to save; to economize; frugal',
  '结账': 'to pay the bill; to settle accounts',
  '解释': 'to explain; to interpret; explanation',
  '今后': 'from now on; in the future; henceforth',
  '仅': 'only; merely; barely',
  '尽管': 'despite; even though; feel free to',
  '仅仅': 'only; merely; just; barely',
  '紧张': 'nervous; tense; intense; tight',
  '进入': 'to enter; to get into; to access',
  '进行': 'to carry out; to conduct; to proceed',
  '禁止': 'to prohibit; to forbid; to ban',
  '精彩': 'wonderful; brilliant; exciting',
  '经济~': '(see 经济)',
  '京剧': 'Beijing opera; Peking opera',
  '经历': 'to experience; to go through; experience',
  '经验~': '(see 经验)',
  '警察': 'police; police officer',
  '景点': 'scenic spot; tourist attraction',
  '景区': 'scenic area; tourist zone',
  '景色': 'scenery; view; landscape',
  '竟然': 'unexpectedly; to one\'s surprise; actually',
  '竞争': 'to compete; competition; rivalry',
  '镜子': 'mirror',
  '究竟': 'after all; actually; exactly; on earth',
  '就是': 'exactly; precisely; that is',
  '举': 'to lift; to raise; to hold up; to cite',
  '举办': 'to hold; to conduct; to host',
  '举例': 'to give an example; for example',
  '举行': 'to hold; to stage; to conduct',
  '聚': 'to gather; to assemble; to get together',
  '聚餐': 'to dine together; dinner party',
  '聚会': 'party; gathering; get-together',
  '拒绝': 'to refuse; to reject; to decline',
  '距离': 'distance; to be apart from; range',
  '剧院': 'theater; playhouse',
  '开玩笑': 'to joke; to make fun of; kidding',
  '看法': 'view; opinion; perspective',
  '烤': 'to roast; to bake; to grill',
  '考虑': 'to consider; to think over; to ponder',
  '考生': 'examinee; candidate; test taker',
  '棵': 'measure word for trees/plants',
  '科技': 'science and technology',
  '科学~': '(see 科学)',
  '咳': 'to cough',
  '咳嗽~': '(see 咳嗽)',
  '可怜': 'pitiful; poor; to have pity on',
  '克': 'gram; to overcome',
  '课程': 'course; curriculum; class',
  '客气': 'polite; courteous; formal',
  '课堂': 'classroom; class',
  '客厅': 'living room; sitting room',
  '肯定': 'certain; sure; definite; to affirm',
  '空': 'empty; hollow; vacant; sky; air (kōng)',
  '空气~': '(see 空气)',
  '恐怕': 'I\'m afraid; perhaps; probably',
  '空': 'free time; empty (kòng)',
  '口语': 'spoken language; oral; colloquial',
  '快递': 'express delivery; courier',
  '快乐~': '(see 快乐)',
  '快速': 'fast; rapid; high-speed',
  '筷子~': '(see 筷子)',
  '宽': 'wide; broad; width; lenient',
  '款': 'style; pattern; funds; section; clause',
  '矿泉水': 'mineral water',
  '困': 'sleepy; tired; to trap; to surround',
  '困难~': '(see 困难)',
  '扩大': 'to expand; to enlarge; to extend',
  '垃圾': 'garbage; trash; rubbish',
  '拉': 'to pull; to drag; to haul; to play (violin)',
  '辣': 'spicy; hot; peppery',
  '来不及': "there's not enough time; too late to",
  '来得及': 'there is still time; can make it',
  '来自~': '(see 来自)',
  '懒': 'lazy; indolent; sluggish',
  '浪费~': '(see 浪费)',
  '浪漫': 'romantic',
  '老鼠': 'mouse; rat',
  '了~': '(particle; see 了)',
  '雷': 'thunder; mine (explosive)',
  '累~': '(see 累)',
  '冷饮': 'cold drink; cold beverage',
  '离婚': 'to divorce; divorce',
  '离开~': '(see 离开)',
  '礼物': 'gift; present',
  '理发': 'haircut; to get a haircut',
  '理解': 'to understand; to comprehend; understanding',
  '理想': 'ideal; dream; aspiration',
  '礼貌': 'politeness; courtesy; manners',
  '礼物~': '(see 礼物)',
  '厉害': 'fierce; formidable; awesome; terrible; severe',
  '利用': 'to use; to utilize; to exploit; to make use of',
  '连忙': 'promptly; at once; immediately; hurriedly',
  '连续': 'continuous; consecutive; in a row',
  '恋爱': 'to be in love; romantic love; love affair',
  '凉~': '(see 凉)',
  '亮': 'bright; light; shiny; to shine',
  '聊天~': '(see 聊天儿)',
  '另外': 'in addition; besides; other; another',
  '留': 'to stay; to remain; to keep; to leave (message)',
  '流': 'to flow; current; stream; class; rate',
  '流利': 'fluent; fluently; smooth',
  '留下': 'to leave behind; to stay; to remain',
  '流行': 'popular; fashionable; prevalent; to spread',
  '路过': 'to pass by; to pass through (a place)',
  '旅馆': 'hotel; inn; hostel',
  '旅客': 'passenger; traveler; tourist',
  '旅行': 'to travel; journey; trip; tour',
  '律师': 'lawyer; attorney',
  '乱': 'messy; chaotic; disorderly; random',
  '落': 'to fall; to drop; to decline; to lag behind',
  '麻烦~': '(see 麻烦)',
  '馒头': 'steamed bun; mantou',
  '满': 'full; filled; satisfied; entire; whole',
  '毛巾~': '(see 毛巾)',
  '毛衣~': '(see 毛衣)',
  '帽子~': '(see 帽子)',
  '美': 'beautiful; pretty; good; America',
  '美好': 'beautiful; fine; glorious; nice',
  '美景': 'beautiful scenery; fine view',
  '美丽~': '(see 美丽)',
  '美食': 'delicacy; gourmet food; fine cuisine',
  '梦': 'dream; to dream',
  '梦想': 'dream; aspiration; to dream of',
  '密码': 'password; secret code; PIN',
  '免费': 'free of charge; free; complimentary',
  '面对': 'to face; to confront; in the face of',
  '面试': 'interview; to interview',
  '秒': 'second (time)',
  '民族~': '(see 民族)',
  '末': 'end; tip; final; last; powder',
  '母女': 'mother and daughter',
  '母亲~': '(see 母亲)',
  '母子': 'mother and son',
  '目标': 'goal; target; objective; aim',
  '目的': 'purpose; aim; goal; objective',
  '目的地': 'destination',
  '目前~': '(see 目前)',
  '耐心': 'patient; patience; to be patient',
  '南部': 'southern part; south',
  '难道': 'could it be that; don\'t tell me...',
  '男士': 'gentleman; man; sir',
  '难受': 'uncomfortable; to feel unwell; hard to bear',
  '难忘': 'unforgettable; memorable',
  '男性': 'male; masculine; man',
  '内': 'inside; inner; within',
  '内容~': '(see 内容)',
  '内心': 'heart; inner heart; innermost being',
  '能否': 'whether or not one can; is it possible',
  '能够': 'can; be able to; be capable of',
  '能力~': '(see 能力)',
  '嗯': 'mm; uh-huh; yeah (interjection)',
  '年底': 'end of the year; year-end',
  '年龄': 'age (of a person)',
  '农村': 'countryside; rural area; village',
  '弄': 'to do; to make; to handle; to get',
  '女性': 'female; woman',
  '暖和~': '(see 暖和)',
  '偶尔': 'occasionally; once in a while; sometimes',
  '拍': 'to pat; to clap; to take (photo); to shoot',
  '排': 'row; line; to arrange; to line up',
  '牌': 'brand; card; plate; sign; tablet',
  '排队': 'to line up; to queue; to wait in line',
  '排球~': '(see 排球)',
  '牌子': 'brand; sign; plate; trademark',
  '判断': 'to judge; to determine; judgment',
  '陪': 'to accompany; to keep company; to go with',
  '批评': 'to criticize; criticism',
  '皮肤': 'skin',
  '脾气': 'temper; temperament; disposition',
  '皮鞋': 'leather shoes',
  '篇': 'measure word for articles/essays/papers',
  '片': 'slice; piece; film; stretch of; measure word',
  '乒乓球': 'table tennis; ping-pong',
  '平常': 'ordinary; common; usually; normally',
  '破': 'broken; damaged; worn out; to break',
  '葡萄~': '(see 葡萄)',
  '葡萄酒': 'wine; grape wine',
  '普遍': 'universal; general; widespread; common',
  '普通~': '(see 普通)',
  '普通话~': '(see 普通话)',
  '期': 'period; phase; stage; term; semester',
  '期末': 'end of term; end of semester',
  '期中': 'mid-term; middle of semester',
  '其次~': '(see 其次)',
  '其中~': '(see 其中)',
  '起到': 'to play a role; to have an effect',
  '气': 'air; gas; breath; spirit; anger',
  '气候': 'climate; weather; atmosphere',
  '汽水': 'soda; soft drink; carbonated drink',
  '气温': 'air temperature; atmospheric temperature',
  '千克': 'kilogram',
  '千万': 'ten million; must; be sure to',
  '签证': 'visa',
  '前方': 'ahead; front; forward',
  '前后': 'around (time); about; front and back; order',
  '强': 'strong; powerful; better; by force',
  '敲': 'to knock; to beat; to strike',
  '桥': 'bridge',
  '巧': 'skillful; clever; coincidental; opportune',
  '巧克力': 'chocolate',
  '亲戚': 'relative; family relation',
  '琴': 'qin (general term for musical instruments)',
  '轻': 'light (weight); gentle; soft; slight',
  '青年': 'youth; young people',
  '轻松': 'relaxed; light; easy; lighthearted',
  '情况': 'situation; condition; circumstance',
  '庆祝': 'to celebrate; celebration',
  '球队': 'sports team; team',
  '球迷': 'fan (sports); enthusiast',
  '区': 'district; area; region; zone',
  '区别': 'difference; distinction; to distinguish',
  '取': 'to take; to get; to fetch; to obtain',
  '取得': 'to obtain; to gain; to acquire; to achieve',
  '取消': 'to cancel; cancellation; to abolish',
  '全': 'whole; entire; total; complete; all',
  '全部~': '(see 全部)',
  '全都': 'all; entirely; without exception',
  '全球': 'global; worldwide; the whole world',
  '全身': 'whole body; all over',
  '缺乏~': '(see 缺乏)',
  '缺': 'to lack; to be short of; missing; vacant',
  '缺点': 'shortcoming; defect; weakness; drawback',
  '缺少': 'to lack; to be short of; shortage',
  '却~': '(see 却)',
  '确实': 'indeed; really; true; certain',
  '然而': 'however; but; yet',
  '人们': 'people; the public; folks',
  '人生': 'life; human life',
  '人数': 'number of people; attendance',
  '人员': 'staff; personnel; crew; member',
  '任何': 'any; whatever; whichever',
  '仍': 'still; yet; to remain; as before',
  '仍然~': '(see 仍然)',
  '日常': 'daily; everyday; routine',
  '日记': 'diary; journal',
  '日期': 'date (calendar)',
  '日子': 'day; date; life; livelihood',
  '入': 'to enter; to join; to be admitted',
  '入口': 'entrance; entry; inlet',
  '入学': 'to enroll; to start school',
  '入住': 'to check in; to move in; to stay',
  '赛': 'match; competition; contest; race',
  '伞': 'umbrella; parasol',
  '散步~': '(see 散步)',
  '扫码': 'to scan a code (QR code)',
  '森林': 'forest; woods',
  '商量': 'to discuss; to consult; to talk over',
  '商品': 'commodity; goods; merchandise; product',
  '伤心': 'sad; heartbroken; grieved; to feel sad',
  '上门': 'to visit; to drop in; door-to-door',
  '稍': 'slightly; a little; a bit; somewhat',
  '稍微': 'a little; slightly; a bit; somewhat',
  '少见': 'rare; seldom seen; uncommon',
  '少量': 'small amount; a little; a few',
  '少数': 'minority; small number; few',
  '少年': 'teenager; juvenile; youngster',
  '社会~': '(see 社会)',
  '摄氏度': 'degree Celsius',
  '身': 'body; life; oneself; personally',
  '深': 'deep; depth; profound; dark (color); late',
  '身份证': 'ID card; identity card',
  '申请': 'to apply; application; to request',
  '甚至~': '(see 甚至)',
  '生': 'to give birth; to be born; life; raw; stranger',
  '生命': 'life; living being; vitality',
  '生意': 'business; trade; deal',
  '省~': '(see 省)',
  '剩': 'to remain; to be left over; surplus',
  '失败': 'to fail; failure; defeat',
  '师傅': 'master; teacher (skilled worker); sir',
  '失去': 'to lose; loss',
  '师生': 'teacher and student; faculty and students',
  '失望': 'to be disappointed; disappointment; despair',
  '十分~': '(see 十分)',
  '实际': 'actual; real; practical; reality',
  '时间表': 'timetable; schedule',
  '实际上': 'in fact; actually; in reality',
  '食品': 'food; foodstuff; provisions',
  '食堂': 'canteen; cafeteria; dining hall',
  '食物': 'food; edibles',
  '实在': 'really; truly; indeed; honest; solid',
  '十字路口': 'crossroads; intersection',
  '使~': '(see 使)',
  '使馆': 'embassy',
  '使用': 'to use; to employ; to apply; usage',
  '市场': 'market; marketplace; bazaar',
  '是否~': '(see 是否)',
  '适合~': '(see 适合)',
  '世纪~': '(see 世纪)',
  '视频': 'video; video clip',
  '市区': 'city proper; urban district; downtown',
  '试题': 'exam question; test question',
  '适应': 'to adapt; to fit; to suit; to adjust',
  '收费~': '(see 收费)',
  '收入~': '(see 收入)',
  '收拾~': '(see 收拾)',
  '收听': 'to listen in; to tune in; to listen to (radio)',
  '首': 'head; chief; first; measure word for poems/songs',
  '首都~': '(see 首都)',
  '首先~': '(see 首先)',
  '受得了': 'can bear; can stand',
  '售票员': 'ticket seller; conductor',
  '受伤~': '(see 受伤)',
  '输': 'to lose; to be defeated; to transport',
  '熟': 'ripe; cooked; done; familiar; skilled',
  '熟悉': 'to know well; to be familiar with; familiar',
  '暑假~': '(see 暑假)',
  '数': 'number; figure; several; to count',
  '数量': 'quantity; amount; number',
  '树林~': '(see 树林)',
  '数字': 'digit; numeral; number; figure; digital',
  '帅~': '(see 帅)',
  '顺便': 'conveniently; by the way; in passing',
  '顺利~': '(see 顺利)',
  '顺序~': '(see 顺序)',
  '说法': 'wording; way of saying; statement; version',
  '说明~': '(see 说明)',
  '说明书': 'manual; instruction booklet; directions',
  '硕士': "master's degree; holder of a master's",
  '死~': '(see 死)',
  '速度~': '(see 速度)',
  '塑料': 'plastic; synthetic material',
  '酸': 'sour; acid; tart; aching',
  '酸奶': 'yogurt; yogurt drink',
  '算~': '(see 算)',
  '随便~': '(see 随便)',
  '随着~': '(see 随着)',
  '孙女': 'granddaughter (son\'s daughter)',
  '孙子': 'grandson (son\'s son)',
  '所有~': '(see 所有)',
  '台~': '(see 台)',
  '抬': 'to lift; to raise; to carry',
  '抬头': 'to raise one\'s head; to look up',
  '态度': 'attitude; manner; approach',
  '弹~': '(see 弹)',
  '谈': 'to talk; to discuss; to chat',
  '汤~': '(see 汤)',
  '躺~': '(see 躺)',
  '趟~': '(see 趟)',
  '讨论': 'to discuss; discussion; to talk over',
  '讨厌': 'to dislike; to hate; annoying; disgusting',
  '特点~': '(see 特点)',
  '提': 'to lift; to raise; to mention; to bring up',
  '提出': 'to put forward; to propose; to raise',
  '提到': 'to mention; to refer to',
  '提供~': '(see 提供)',
  '提前~': '(see 提前)',
  '提醒~': '(see 提醒)',
  '体检~': '(see 体检)',
  '体温~': '(see 体温)',
  '体重': 'body weight; weight',
  '填写': 'to fill in; to write; to complete (form)',
  '条件~': '(see 条件)',
  '听力': 'listening comprehension; hearing ability',
  '听众': 'audience; listeners',
  '停': 'to stop; to halt; to pause; to park',
  '停车': 'to park; to stop a vehicle; parking',
  '停车场': 'parking lot; car park',
  '停止': 'to stop; to cease; to halt',
  '通': 'to go through; to connect; open; through',
  '通过~': '(see 通过)',
  '通知~': '(see 通知)',
  '童年~': '(see 童年)',
  '同时~': '(see 同时)',
  '同样': 'same; similar; equally; likewise',
  '桶': 'bucket; barrel; tub; pail',
  '痛': 'painful; ache; sore; deeply',
  '头痛': 'headache; to have a headache',
  '图': 'picture; drawing; chart; map; diagram',
  '图片': 'picture; image; photograph',
  '土': 'earth; soil; dust; land; local; rustic',
  '推': 'to push; to shove; to promote; to infer',
  '推迟~': '(see 推迟)',
  '推出~': '(see 推出)',
  '脱~': '(see 脱)',
  '袜子~': '(see 袜子)',
  '外出': 'to go out; to be away from home',
  '外套': 'coat; jacket; outer garment',
  '完全~': '(see 完全)',
  '晚安': 'good night; good evening',
  '晚餐': 'dinner; supper; evening meal',
  '网购': 'online shopping',
  '往往': 'often; frequently; more often than not',
  '网页': 'web page; webpage',
  '网友': 'online friend; netizen; internet buddy',
  '网址': 'website address; URL',
  '危险': 'dangerous; danger; peril; risk',
  '为': 'for; to; for the sake of; to do; to act as',
  '味': 'taste; flavor; smell; odor',
  '味道': 'taste; flavor; smell',
  '卫生': 'hygiene; sanitation; health',
  '温度': 'temperature',
  '闻': 'to smell; to sniff; to hear (news)',
  '文件': 'document; file; papers',
  '文章~': '(see 文章)',
  '文字': 'written characters; writing; script; text',
  '污染': 'pollution; to pollute; to contaminate',
  '无': 'without; no; not; nothing; regardless of',
  '无法': 'unable; incapable; no way to',
  '无聊': 'boring; dull; bored; silly',
  '无论~': '(see 无论)',
  '午餐': 'lunch; midday meal',
  '误会': 'misunderstanding; to misunderstand; mistake',
  '吸': 'to inhale; to breathe in; to absorb; to suck',
  '西部': 'western part; west; western region',
  '西红柿': 'tomato',
  '吸引': 'to attract; to draw; to fascinate; attraction',
  '细': 'thin; slender; fine; delicate; detailed; careful',
  '细心': 'careful; attentive; meticulous',
  '下降': 'to descend; to drop; to fall; to decline',
  '鲜': 'fresh; delicious; bright; tasty',
  '鲜花': 'fresh flower; bouquet',
  '咸': 'salty; salted',
  '现金': 'cash; ready money',
  '羡慕': 'to envy; to admire; envy; admiration',
  '线上': 'online; on the line; above the line',
  '线下': 'offline; below the line',
  '现有': 'existing; currently available',
  '香~': '(see 香)',
  '相比': 'to compare; compared with; comparison',
  '相反~': '(see 相反)',
  '相互': 'mutual; reciprocal; each other',
  '相同~': '(see 相同)',
  '详细': 'detailed; in detail; thorough; elaborate',
  '响~': '(see 响)',
  '想法': 'idea; thought; opinion; way of thinking',
  '项': 'item; project; term; measure word',
  '消息~': '(see 消息)',
  '小吃~': '(see 小吃)',
  '小伙子~': '(see 小伙子)',
  '小说~': '(see 小说)',
  '小组': 'group; team; small group; panel',
  '效果': 'effect; result; outcome; effectiveness',
  '笑话~': '(see 笑话)',
  '血': 'blood',
  '心': 'heart; mind; feeling; center',
  '辛苦': 'hard; laborious; toilsome; to work hard',
  '心情': 'mood; state of mind; frame of mind',
  '信号': 'signal; sign; beacon',
  '信息~': '(see 信息)',
  '信心~': '(see 信心)',
  '兴奋~': '(see 兴奋)',
  '星星~': '(see 星星)',
  '醒': 'to wake up; to awaken; to sober up',
  '性': 'gender; sex; nature; character; property',
  '性别': 'gender; sex; sexual distinction',
  '幸福': 'happy; happiness; blessed; well-being',
  '性格': 'character; personality; nature; disposition',
  '兄弟': 'brothers; brethren; buddy; bro',
  '熊': 'bear',
  '修': 'to repair; to fix; to mend; to study; to build',
  '修理': 'to repair; to fix; to mend; to overhaul',
  '许多': 'many; much; a lot of; numerous',
  '学费': 'tuition; school fees',
  '学院': 'college; institute; academy; school',
  '压': 'to press; to push down; to suppress; pressure',
  '压力~': '(see 压力)',
  '牙膏~': '(see 牙膏)',
  '亚洲~': '(see 亚洲)',
  '烟': 'smoke; cigarette; tobacco; mist',
  '盐': 'salt',
  '严格': 'strict; rigorous; stringent; stern',
  '研究': 'to research; to study; research; study',
  '研究生~': '(see 研究生)',
  '严重~': '(see 严重)',
  '演': 'to perform; to act; to play; to evolve',
  '演唱': 'to sing; vocal performance; concert',
  '演出~': '(see 演出)',
  '眼镜': 'glasses; eyeglasses; spectacles',
  '眼前': 'before one\'s eyes; at present; now',
  '演员~': '(see 演员)',
  '阳光~': '(see 阳光)',
  '养成': 'to form; to cultivate; to develop (habit)',
  '样子~': '(see 样子)',
  '邀请~': '(see 邀请)',
  '要是~': '(see 要是)',
  '钥匙~': '(see 钥匙)',
  '也许~': '(see 也许)',
  '夜': 'night; evening; dark',
  '夜晚': 'night; nighttime; evening',
  '叶子~': '(see 叶子)',
  '一切~': '(see 一切)',
  '已': 'already; to stop; to cease; to finish',
  '以内': 'within; inside; less than',
  '意见~': '(see 意见)',
  '一生': 'all one\'s life; throughout one\'s life; lifetime',
  '艺术': 'art; skill; craft; technique',
  '因此~': '(see 因此)',
  '引起~': '(see 引起)',
  '印象~': '(see 印象)',
  '赢~': '(see 赢)',
  '赢得': 'to win; to gain; to earn; to obtain',
  '应聘': 'to apply for a job; to accept a job offer',
  '勇敢~': '(see 勇敢)',
  '永远~': '(see 永远)',
  '用来': 'used for; for the purpose of; to be used to',
  '用于': 'to be used in/for; to apply to',
  '优点~': '(see 优点)',
  '幽默': 'humorous; humor; funny',
  '优秀': 'excellent; outstanding; superior',
  '由~': '(see 由)',
  '油': 'oil; fat; grease; fuel; paint',
  '尤其~': '(see 尤其)',
  '游玩': 'to play; to amuse oneself; to go sightseeing',
  '由于~': '(see 由于)',
  '友好~': '(see 友好)',
  '友情': 'friendship; camaraderie; friendly feelings',
  '有趣~': '(see 有趣)',
  '有效~': '(see 有效)',
  '友谊~': '(see 友谊)',
  '有着': 'to have; to possess; to be endowed with',
  '愉快': 'happy; pleasant; delightful; cheerful',
  '于是~': '(see 于是)',
  '与': 'and; with; to; to give',
  '语法~': '(see 语法)',
  '预习~': '(see 预习)',
  '原来': 'originally; formerly; as it turns out; so',
  '原谅': 'to forgive; to excuse; to pardon; forgiveness',
  '原因': 'reason; cause; origin; grounds',
  '远离': 'far away from; to keep away from; distant',
  '院长': 'dean; president; director; superintendent',
  '院子': 'courtyard; yard; compound',
  '约': 'to arrange; to make an appointment; about; around',
  '约会': 'appointment; date; engagement; to date',
  '月饼': 'mooncake (Mid-Autumn Festival treat)',
  '阅读': 'to read; reading',
  '月份': 'month (of the year)',
  '云': 'cloud',
  '允许': 'to allow; to permit; permission; to grant',
  '杂志': 'magazine; journal; periodical',
  '再次': 'once again; once more; a second time',
  '再说': 'besides; what\'s more; to talk about later',
  '暂时': 'temporary; for the time being; temporarily',
  '暂停': 'to suspend; to pause; suspension; timeout',
  '早餐': 'breakfast; morning meal',
  '早晨': 'early morning; morning',
  '责任': 'responsibility; duty; liability; blame',
  '增加': 'to increase; to add; to raise; to grow',
  '增长': 'to grow; to increase; growth; rise',
  '招聘': 'to recruit; to hire; recruitment; job opening',
  '着': 'ongoing action marker; to be in a state of',
  '着火': 'to catch fire; to be on fire',
  '者': '-er; -ist; one who...; person',
  '真正~': '(see 真正)',
  '整': 'whole; entire; full; exactly; to repair; to fix',
  '整个': 'whole; entire; total; completely',
  '整理': 'to arrange; to tidy up; to sort out; to organize',
  '证': 'certificate; proof; evidence; to prove',
  '正常': 'normal; regular; ordinary; usual',
  '正好': 'just right; just in time; coincidentally',
  '证件': 'certificate; credentials; papers; ID',
  '证明': 'to prove; to testify; proof; certificate; evidence',
  '正确': 'correct; right; proper; accurate',
  '正式': 'formal; official; regular; proper',
  '之': 'of; it; him; her; them; to go; to leave',
  '支持': 'to support; to back; support; backing',
  '支付': 'to pay; payment; to defray',
  '之后': 'after; afterwards; later; behind',
  '之间': 'between; among',
  '之前': 'before; prior to; ago; in front of',
  '知识': 'knowledge; learning; intellectual',
  '之中': 'among; in the midst of; in; inside',
  '值': 'value; worth; to be worth; to cost',
  '值得': 'to be worth; to deserve; worthwhile',
  '直接': 'direct; directly; straight; immediate',
  '植物': 'plant; vegetation; botanical',
  '职业': 'occupation; profession; vocation; career',
  '指': 'to point; to refer to; finger; to indicate',
  '指出': 'to point out; to indicate; to note',
  '只好': 'have to; be forced to; can only',
  '纸巾': 'tissue; paper towel; napkin',
  '质量': 'quality; mass (physics)',
  '至少': 'at least; at the minimum',
  '中餐': 'Chinese food; Chinese cuisine; lunch',
  '中年': 'middle age; middle-aged',
  '种': 'kind; type; sort; species; seed; to plant',
  '重': 'heavy; weight; serious; important (zhòng)',
  '重点': 'key point; focus; emphasis; important',
  '重视': 'to value; to attach importance to; to respect',
  '周围': 'surroundings; around; vicinity; neighborhood',
  '主意': 'idea; plan; decision; definite view',
  '祝': 'to wish; to express good wishes; to pray',
  '祝贺': 'to congratulate; congratulations; to celebrate',
  '著名': 'famous; celebrated; well-known; renowned',
  '专门': 'specially; specialized; special; expert',
  '专业': 'major; specialty; profession; professional',
  '转': 'to turn; to rotate; to transfer; to change',
  '转发': 'to forward; to relay; to transmit; to repost',
  '赚': 'to earn; to make a profit; to gain',
  '装': 'to load; to pack; to install; to pretend',
  '准': 'accurate; exact; precise; to allow; standard',
  '准确': 'accurate; exact; precise; precision',
  '准时': 'on time; punctual; prompt',
  '资料': 'material; data; resources; information',
  '仔细': 'careful; attentive; meticulous; cautious',
  '自': 'self; oneself; from; since; naturally',
  '自然': 'nature; natural; naturally; of course',
  '自习': 'to study by oneself; self-study',
  '自信': 'self-confident; confidence; self-assurance',
  '自学': 'self-study; to study independently',
  '总结': 'to summarize; to sum up; summary; conclusion',
  '租': 'to rent; to hire; to lease; rental',
  '组': 'group; team; to organize; to form; set',
  '最终': 'final; ultimate; eventually; in the end',
  '尊重': 'to respect; to value; respect; esteem',
  '左右': 'about; approximately; left and right; around',
  '座': 'seat; place; stand; pedestal; measure word',
  '做法': 'way of doing things; method; practice; approach',
  '作家': 'writer; author',
  '做梦': 'to dream; to have a dream; daydream',
  '作品': 'work; works; opus; production; piece',
  '作为': 'as; in the capacity of; to regard as; conduct',
  '座位': 'seat; place',
  '作文': 'composition; essay; writing',
  '作用': 'function; effect; role; action; purpose',
  '作者': 'author; writer; composer',

  // === FINAL SUPPLEMENT ===
  '吧': 'modal particle; let\'s; okay; bar',
  '白天': 'daytime; during the day',
  '边': 'side; edge; border; simultaneously',
  '病': 'illness; disease; to be sick',
  '唱': 'to sing',
  '超市': 'supermarket',
  '大家': 'everyone; everybody; all',
  '大学生': 'university/college student',
  '第': 'ordinal prefix (first, second, etc.)',
  '电话': 'telephone; phone call',
  '电影院': 'cinema; movie theater',
  '读书': 'to read; to study',
  '儿子': 'son',
  '饭': 'meal; cooked rice; food',
  '公司': 'company; corporation; firm',
  '工作': 'work; job; to work',
  '狗': 'dog',
  '好看': 'good-looking; nice; pretty',
  '好听': 'pleasant to hear; nice sounding',
  '好玩儿': 'fun; amusing; interesting',
  '后': 'after; behind; back; rear',
  '火车': 'train',
  '鸡蛋': 'chicken egg',
  '家人': 'family members',
  '见': 'to see; to meet; to catch sight of',
  '今年': 'this year',
  '开车': 'to drive a car',
  '看病': 'to see a doctor; to treat illness',
  '两': 'two; both (with measure words)',
  '吗': 'question particle',
  '卖': 'to sell',
  '没事': 'it\'s nothing; no problem; never mind',
  '们': 'plural marker for pronouns/people',
  '面包': 'bread',
  '面条儿': 'noodles',
  '明年': 'next year',
  '哪个': 'which one',
  '哪些': 'which ones; what (plural)',
  '那边': 'over there; that side',
  '那个': 'that one; that',
  '那些': 'those',
  '男朋友': 'boyfriend',
  '你好': 'hello; hi',
  '您': 'you (polite/honorific)',
  '女朋友': 'girlfriend',
  '女士': 'lady; madam; Ms.',
  '便宜': 'cheap; inexpensive',
  '起床': 'to get up; to get out of bed',
  '前': 'front; before; ago; previous',
  '去年': 'last year',
  '日': 'day; sun; date',
  '上课': 'to go to class; to attend class',
  '谁': 'who; whom',
  '事': 'matter; thing; affair; event',
  '书店': 'bookstore; bookshop',
  '岁': 'year (of age); years old',
  '它': 'it',
  '它们': 'they; them (for animals/things)',
  '听见': 'to hear; to catch the sound of',
  '外边': 'outside; outer',
  '晚': 'late; evening; night',
  '晚饭': 'dinner; evening meal',
  '午饭': 'lunch; midday meal',
  '下班': 'to get off work; to finish work',
  '小朋友': 'child; kid; little friend',
  '小学': 'elementary school; primary school',
  '星期天': 'Sunday',
  '学习': 'to study; to learn; learning',
  '雪': 'snow',
  '一半': 'half; one half',
  '一下': 'once; a little while; briefly',
  '一些': 'some; a few; a little',
  '有的': 'some; there are some',
  '有点儿': 'a little; somewhat; a bit',
  '有些': 'some; somewhat; there are some',
  '元': 'yuan (Chinese currency); unit',
  '再': 'again; once more; then; further',
  '早饭': 'breakfast',
  '这边': 'this side; here; over here',
  '这个': 'this; this one',
  '这些': 'these',
  '中午': 'noon; midday',
  '中学': 'middle school; secondary school',
  '中学生': 'middle school student',
  '帮': 'to help; to assist; gang; group',
  '不错': 'not bad; pretty good; right',
  '出国': 'to go abroad',
  '出来': 'to come out; to emerge; to appear',
  '出门': 'to go out; to leave home; to travel',
  '词': 'word; term; vocabulary',
  '次': 'time; occurrence; measure word for times',
  '从小': 'from childhood; since childhood',
  '打车': 'to take a taxi',
  '但': 'but; however; yet',
  '地': 'earth; land; ground; place (dì)',
  '地铁': 'subway; metro; underground',
  '懂': 'to understand; to comprehend',
  '动': 'to move; to act; movement; motion',
  '飞': 'to fly; flight',
  '高中': 'senior high school',
  '跟': 'with; to follow; and; heel',
  '过年': 'to celebrate the New Year',
  '黑色': 'black (color)',
  '红茶': 'black tea',
  '红色': 'red (color)',
  '机票': 'airline ticket; plane ticket',
  '记得': 'to remember; to recall',
  '间': 'between; among; room; measure word',
  '酒店': 'hotel; restaurant',
  '咖啡': 'coffee',
  '开学': 'to start school; school opens',
  '考': 'to test; to examine; exam',
  '裤子': 'trousers; pants',
  '快要': 'about to; soon; almost',
  '篮球': 'basketball',
  '离': 'to leave; to depart; from; away from',
  '里面': 'inside; interior',
  '楼': 'building; floor; storey',
  '路上': 'on the road; on the way',
  '绿茶': 'green tea',
  '没意思': 'boring; uninteresting',
  '每': 'every; each; per',
  '门': 'door; gate; entrance; measure word',
  '门票': 'admission ticket; entrance ticket',
  '名': 'name; fame; reputation; measure word',
  '那么': 'so; like that; then',
  '那样': 'like that; that way; such',
  '奶茶': 'milk tea',
  '男孩儿': 'boy; little boy',
  '女孩儿': 'girl; little girl',
  '跑': 'to run',
  '票': 'ticket; ballot; vote',
  '妻子': 'wife',
  '晴': 'clear; sunny; fine (weather)',
  '球': 'ball; sphere; globe',
  '肉': 'meat; flesh',
  '商场': 'shopping mall; market; department store',
  '上来': 'to come up',
  '上面': 'above; on top of; over',
  '上去': 'to go up',
  '上网': 'to go online; to surf the Internet',
  '时': 'time; hour; moment; when',
  '手表': 'wristwatch; watch',
  '书包': 'schoolbag; backpack',
  '舒服': 'comfortable; feeling well',
  '送': 'to send; to deliver; to give as a gift',
  '题': 'topic; problem; question; subject',
  '条': 'strip; item; measure word for long things',
  '头': 'head; top; first; leading',
  '万': 'ten thousand; myriad; a great number',
  '往': 'toward; to; to go; past',
  '网上': 'online; on the Internet',
  '位': 'measure word for people (polite); position; place',
  '洗': 'to wash; to bathe; to clean',
  '洗手间': 'restroom; bathroom; washroom',
  '下来': 'to come down',
  '下面': 'below; under; underneath; next',
  '下去': 'to go down; to descend',
  '小孩儿': 'child; little kid',
  '小时候': 'in one\'s childhood; when one was young',
  '姓': 'surname; family name; to be surnamed',
  '姓名': 'full name; surname and given name',
  '药店': 'pharmacy; drugstore',
  '一会儿': 'a little while; a moment; soon',
  '阴': 'cloudy; overcast; yin; shade',
  '游': 'to swim; to travel; to roam',
  '有意思': 'interesting; fun; meaningful',
  '有时': 'sometimes',
  '右': 'right; right side',
  '鱼': 'fish',
  '运动': 'sport; exercise; movement; to move',
  '丈夫': 'husband',
  '这么': 'so; such; this way; like this',
  '这样': 'this way; like this; so; such',
  '正': 'straight; upright; just; exactly; correct',
  '周': 'week; circumference; cycle',
  '足球': 'football; soccer',
  '左': 'left; left side',
  '矮': 'short (in height); low',
  '爱人': 'spouse; husband or wife; lover',
  '搬': 'to move; to remove; to transport',
  '班级': 'class (in school); grade',
  '搬家': 'to move (house)',
  '办': 'to do; to manage; to handle; to run',
  '半天': 'half a day; a long time; quite a while',
  '饱': 'full (after eating); satisfied',
  '北': 'north',
  '被': 'by (passive marker); quilt; to be covered',
  '笔记': 'notes; to take notes',
  '笔记本': 'notebook; laptop',
  '比如': 'for example; such as',
  '别的': 'other; else',
  '宾馆': 'hotel; guesthouse',
  '冰': 'ice',
  '冰激凌': 'ice cream',
  '冰箱': 'refrigerator; freezer',
  '病人': 'patient; sick person',
  '不见': 'to disappear; to not see; be missing',
  '不用': 'no need to; don\'t have to',
  '不行': 'not OK; not allowed; no good',
  '才': 'just; only; not until; talent; ability',
  '菜单': 'menu',
  '草地': 'lawn; grassland; meadow',
  '层': 'layer; level; floor; storey',
  '查': 'to check; to look up; to investigate',
  '差': 'to differ from; lacking; poor; bad',
  '差不多': 'almost; nearly; more or less; about',
  '尝': 'to taste; to try (food)',
  '常': 'often; frequently; common; ordinary',
  '常见': 'common; frequently seen',
  '常用': 'commonly used; in common use',
  '常常': 'often; frequently; usually',
  '衬衫': 'shirt; blouse',
  '成绩': 'achievement; result; grades (school)',
  '迟到': 'to be late; to arrive late',
  '出发': 'to set out; to depart; to start off',
  '出院': 'to leave hospital; to be discharged',
  '初中': 'junior high school; middle school',
  '船': 'boat; ship; vessel',
  '春天': 'spring (season)',
  '词典': 'dictionary',
  '聪明': 'clever; intelligent; smart; bright',
  '打扫': 'to clean; to sweep; to tidy up',
  '打算': 'to plan; to intend; plan; intention',
  '大概': 'probably; roughly; approximately; general idea',
  '大人': 'adult; grown-up',
  '大小': 'size; dimension; magnitude',
  '大熊猫': 'giant panda',
  '大衣': 'overcoat; coat',
  '到处': 'everywhere; all over',
  '得分': 'score; to score points',
  '的话': 'if (conditional); in the case of',
  '地点': 'place; location; site; venue',
  '地图': 'map',
  '电': 'electricity; electric; lightning',
  '电子书': 'e-book; electronic book',
  '丢': 'to lose; to throw; to discard',
  '东北': 'northeast',
  '冬天': 'winter (season)',
  '耳朵': 'ear',
  '方向': 'direction; orientation; course; bearing; aspect; trend',
  '复习': 'to review; to revise; revision',
  '干净': 'clean; neat; tidy',
  '刚': 'just; just now; exactly; barely',
  '刚刚': 'just now; a moment ago; just',
  '根据': 'according to; based on; on the basis of; basis; grounds; evidence',
  '故事': 'story; tale; plot',
  '关系': 'relationship; relation; connection; bearing; to affect; to concern',
  '关心': 'to care about; to be concerned',
  '关于': 'about; concerning; regarding; on',
  '海': 'sea; ocean; huge',
  '害怕': 'to be afraid; to be scared; fear',
  '季节': 'season',
  '加': 'to add; to increase; plus',
  '坚持': 'to persist; to insist on; to uphold',
  '检查': 'to check; to examine; to inspect; inspection',
  '脚': 'foot; leg; base; foundation',
  '节目': 'program; show; item; performance',
  '开会': 'to hold a meeting; to attend a meeting',
  '看来': 'it seems; it looks like; apparently',
  '可是': 'but; however; yet',
  '老': 'old; aged; experienced; always; prefix',
  '老人': 'old person; the elderly; aged',
  '马': 'horse',
  '满意': 'satisfied; pleased; content; satisfaction',
  '身边': 'at one\'s side; on hand; around',
  '声音': 'sound; voice; noise; tone',
  '试': 'to try; to test; to attempt; experiment',
  '受到': 'to receive; to suffer; to be subjected to; to incur; to be affected by',
  '水平': 'level; standard; horizontal; proficiency; grade',
  '文化': 'culture; civilization; cultural; education; literacy',
  '行李': 'luggage; baggage',
  '邮件': 'mail; email; post',
  '安排': 'to arrange; to plan; to set up; arrangement; plan',
  '表现': 'to show; to display; to manifest; performance; behavior',
  '并': 'and; also; simultaneously; equally; actually (emphatic)',
  '不断': 'unceasing; uninterrupted; continuous; constantly; unceasingly',
  '不仅': 'not only; not just; not merely',
  '此': 'this; these; here; now',
  '翻译': 'to translate; translator; interpretation; translation',
  '方面': 'aspect; respect; side; field; area; facet',
  '复杂': 'complex; complicated; intricate; sophisticated',
  '干杯': 'cheers!; bottoms up!; toast',
  '赶': 'to catch up; to rush; to hurry; to drive away',
  '感动': 'to move (emotionally); to touch; to be moved; touched',
  '感觉': 'to feel; to sense; to perceive; feeling; sense; sensation; perception',
  '工人': 'worker; workman; laborer',
  '估计': 'to estimate; to reckon; to appraise; estimation; assessment',

  // === FINAL BATCH SUPPLEMENT ===
  '一块儿': 'together; in one place; at the same place',
  '一般': 'generally; ordinary; common; same as; usually',
  '一边': 'one side; while; at the same time; simultaneously',
  '上衣': 'upper garment; jacket; top; coat',
  '不便': 'inconvenient; inappropriate; unsuitable',
  '不光': 'not only; not just; not merely',
  '不够': 'not enough; insufficient; inadequate',
  '不如': 'not as good as; inferior to; it would be better to',
  '不得不': 'have to; cannot but; have no choice but to',
  '不必': 'need not; not have to; unnecessary',
  '不满': 'dissatisfied; discontented; resentful; dissatisfaction',
  '不管': 'no matter; regardless of; despite; whether',
  '东南': 'southeast',
  '东方': 'east; the Orient; eastern',
  '东部': 'eastern part; east',
  '为了': 'for; in order to; for the sake of',
  '乘': 'to ride; to take (transport); to multiply; to avail oneself of',
  '乘坐': 'to ride; to travel by (vehicle)',
  '乘客': 'passenger',
  '从中': 'from among; from within; therefrom',
  '从此': 'from now on; from then on; henceforth',
  '付': 'to pay; to hand over; to give',
  '以上': 'above; more than; the above; over',
  '以下': 'below; under; the following; less than',
  '以外': 'apart from; beyond; outside; other than; except',
  '休假': 'to take a vacation; vacation; holiday; leave',
  '会议': 'meeting; conference; convention; assembly',
  '低于': 'lower than; below; less than',
  '低价': 'low price; cheap',
  '低温': 'low temperature',
  '体育馆': 'gymnasium; sports hall; stadium',
  '便于': 'convenient for; easy to; in order to facilitate',
  '信': 'letter; mail; to believe; to trust; message; faith',
  '信用卡': 'credit card',
  '倍': 'times; -fold; double; to multiply',
  '借': 'to borrow; to lend; to make use of',
  '假期': 'holiday; vacation; leave; break',
  '像': 'to resemble; to be like; such as; image; portrait',
  '先': 'first; earlier; before; in advance; for the time being',
  '公斤': 'kilogram (kg)',
  '公路': 'highway; road; public road',
  '公里': 'kilometer',
  '共': 'together; common; general; altogether; to share',
  '关机': 'to turn off; to shut down (machine); to power off',
  '关注': 'to follow with interest; to pay attention to; to concern',
  '兴趣': 'interest; hobby; enjoyment',
  '养': 'to raise; to keep; to grow; to support; to cultivate',
  '凉快': 'nice and cool; pleasantly cool; refreshing',
  '出差': 'to go on a business trip',
  '出租': 'to rent out; to let; to hire; rental; taxi (short for)',
  '出行': 'to go out; to travel; to go on a trip; outing',
  '刀': 'knife; blade; sword; measure word for cuts/knife strikes',
  '分为': 'to divide into; to separate into; to be classified as',
  '分开': 'to separate; to part; to split; separately; apart',
  '分数': 'score; mark; grade; fraction; points',
  '刚才': 'just now; a moment ago; just a while ago',
  '刮': 'to scrape; to blow (wind); to shave; to extort',
  '到来': 'to arrive; arrival; advent; coming',
  '刷': 'to brush; to scrub; to paint; to swipe (card); to eliminate',
  '刻': 'to carve; to engrave; quarter (of an hour); moment; unkind',
  '前天': 'the day before yesterday',
  '前年': 'the year before last',
  '办事': 'to handle affairs; to work; to run errands',
  '办公': 'to work (in an office); to handle official business',
  '办理': 'to handle; to deal with; to conduct; to transact',
  '动物园': 'zoo; zoological garden',
  '动车': 'high-speed train; bullet train; EMU (electric multiple unit)',
  '勺子': 'spoon; ladle; scoop',
  '北部': 'northern part; north; northern region',
  '南': 'south',
  '南方': 'south; southern part; the South',
  '卡': 'card; to block; to be stuck; calorie; checkpoint',
  '卫生间': 'bathroom; restroom; toilet; lavatory',
  '厂': 'factory; plant; mill; yard; works',
  '厕所': 'toilet; lavatory; restroom; bathroom',
  '厨师': 'chef; cook; kitchen worker',
  '参赛': 'to participate in a competition; to compete',
  '双': 'pair; double; twin; two; both; dual',
  '发': 'to send out; to emit; to deliver; to develop; to occur; hair',
  '发出': 'to send out; to issue; to emit; to give out; to produce',
  '发生': 'to happen; to occur; to take place',
  '发送': 'to send; to transmit; to dispatch; to distribute',
  '叔叔': 'uncle (father\'s younger brother); uncle (form of address)',
  '受': 'to receive; to accept; to suffer; to endure; to be subjected to',
  '句': 'sentence; phrase; measure word for sentences/utterances',
  '句子': 'sentence; clause; phrase',
  '可': 'can; may; able to; but; yet; to approve; to permit; worthwhile',
  '可惜': 'it\'s a pity; unfortunately; what a pity',
  '可爱': 'cute; lovely; adorable; lovable',
  '号码': 'number; code; size',
  '司机': 'driver; chauffeur',
  '吃惊': 'to be surprised; to be shocked; to be startled; amazed',
  '各': 'each; every; various; different; all',
  '各个': 'each; every; various; one by one; individually',
  '各位': 'everyone; everybody; all (polite address); each; every',
  '各地': 'everywhere; various places; all parts of',
  '各种': 'all kinds of; various; every kind of; a variety of',
  '合适': 'suitable; appropriate; fitting; right',
  '同事': 'colleague; coworker; fellow worker',
  '名人': 'famous person; celebrity; notable; public figure',
  '名单': 'name list; roster; roll',
  '后天': 'the day after tomorrow; acquired; postnatal',
  '后年': 'the year after next',
  '后来': 'later; afterwards; subsequently; afterward; then',
  '向': 'toward; to; direction; to face; to be partial to; always',
  '员': 'member; person; staff; personnel; -er (suffix)',
  '喜爱': 'to like; to love; to be fond of; to favor; favorite',
  '四季': 'the four seasons; all year round',
  '回复': 'to reply; to answer; to respond; to recover; to return to normal',
  '园': 'garden; park; orchard; place for public recreation',
  '地址': 'address; location; site',
  '场': 'field; place; stage; scene; market; large place; measure word',
  '城': 'city; town; city wall; urban area',
  '堵车': 'traffic jam; traffic congestion; to be stuck in traffic',
  '声': 'sound; voice; noise; tone; reputation; measure word for sounds',
  '复印': 'to photocopy; to duplicate; to copy; photocopy',
  '夏天': 'summer; summertime',
  '外卖': 'takeout; delivery (food); to go',
  '外地': 'other places; another locality; not local; out of town',
  '外语': 'foreign language',
  '多数': 'majority; most; majority of; greater number',
  '多样': 'diverse; varied; various; multiple; diversity',
  '大厅': 'hall; lobby; main hall; large room',
  '大大': 'greatly; enormously; greatly; considerably; much',
  '大夫': 'doctor; physician',
  '大巴': 'bus; coach; large bus',
  '大自然': 'nature; the natural world',
  '大赛': 'major competition; big contest; championship',
  '夫妻': 'husband and wife; married couple',
  '头发': 'hair (on the head)',
  '奇怪': 'strange; odd; weird; surprising; curious; peculiar',
  '女生': 'female student; schoolgirl; girl',
  '好久': 'a long time; quite a while; for a long time',
  '好多': 'many; a lot of; quite a lot; much; so many',
  '姐妹': 'sisters; sisters and brothers; female siblings',
  '姑娘': 'girl; young woman; maiden; daughter',
  '季': 'season; quarter; period; last month of a season',
  '安检': 'security check; safety inspection',
  '定': 'to set; to fix; to determine; to decide; to order; stable; calm; surely',
  '客人': 'guest; visitor; customer; patron; caller',
  '室': 'room; chamber; office; work unit',
  '对于': 'regarding; concerning; as for; in regard to; toward',
  '对话': 'dialogue; conversation; to have a dialogue',
  '对面': 'opposite; across from; directly facing; the other side',
  '导游': 'tour guide; guide; to guide a tour',
  '封': 'to seal; to close; to block; envelope; measure word for letters',
  '小区': 'residential community; neighborhood; housing estate; compound',
  '小心': 'to be careful; to be cautious; careful; cautious; look out',
  '屋子': 'room; house; building',
  '山': 'mountain; hill; anything resembling a mountain',
  '工作日': 'working day; workday; business day; weekday',
  '差点儿': 'almost; nearly; not quite; on the verge of',
  '市': 'city; municipality; market; metropolitan area',
  '幅': 'measure word for pictures, paintings, scrolls, cloth, etc.',
  '年轻': 'young; youthful',
  '底': 'bottom; base; foundation; background; end (of month/year)',
  '底下': 'under; beneath; below; underneath; next; later',
  '度假': 'to go on vacation; to spend holidays; to vacation',
  '开机': 'to turn on; to start up (machine); to boot up; to power on',
  '开花': 'to bloom; to blossom; to flower; to flourish; to explode',
  '当': 'to serve as; to work as; when; at that time; to face; should; ought to',
  '当时': 'at that time; then; at the time',
  '待': 'to wait; to stay; to treat; to deal with; to need; about to',
  '得意': 'proud of oneself; pleased with oneself; complacent; smug',
  '心里': 'in one\'s heart; in one\'s mind; inwardly; at heart',
  '忘记': 'to forget',
  '怕': 'to fear; to be afraid of; to dread; perhaps; probably',
  '感': 'to feel; to sense; to move (emotionally); feeling; sense; emotion',
  '感人': 'moving; touching; emotionally affecting',
  '感冒': 'to catch a cold; common cold; to be interested in',
  '愿意': 'to be willing; to want to; to be ready to; to agree',
  '懂得': 'to understand; to know; to comprehend',
  '成功': 'to succeed; success; successful; to achieve',
  '或': 'or; either; perhaps; maybe; possibly; someone',
  '戴': 'to wear (on head/face/wrist); to put on; to respect; to support',
  '房东': 'landlord; landlady; property owner',
  '房租': 'rent; house rent; rental fee',
  '打印机': 'printer (computer)',
  '打工': 'to work part-time; to do manual labor; to work a temporary job',
  '打扰': 'to disturb; to bother; to trouble; to interrupt',
  '打折': 'to give a discount; to sell at a discount; discount',
  '打败': 'to defeat; to beat; to overcome; to be defeated',
  '打针': 'to give or receive an injection; to have an injection',
  '扔': 'to throw; to toss; to throw away; to cast aside',
  '扫': 'to sweep; to clear away; to scan; to glance',
  '报考': 'to register for an exam; to apply to take a test; to sign up for',
  '抱': 'to hold; to embrace; to hug; to carry in one\'s arms; to cherish',
  '抱歉': 'to be sorry; to regret; to feel apologetic; sorry; regretful',
  '拍照': 'to take a photo; to photograph; to take a picture',
  '按': 'to press; to push; to follow; according to; to restrain; based on',
  '按时': 'on time; on schedule; punctually',
  '按照': 'according to; in accordance with; in the light of; based on',
  '挺': 'quite; very; rather; to stick out; to endure; to hold out; straight',
  '提高': 'to raise; to increase; to improve; to heighten; to enhance',
  '播放': 'to broadcast; to play (media); to transmit; to air',
  '操场': 'playground; sports ground; sports field; drill ground',
  '擦': 'to wipe; to rub; to clean; to polish; to erase; to scrape; to brush',
  '收': 'to receive; to accept; to collect; to gather; to harvest; to put away',
  '收到': 'to receive; to get; to achieve; to obtain (message/package)',
  '改': 'to change; to alter; to correct; to revise; to improve; to switch',
  '放学': 'to finish school for the day; to finish classes; school is over',
  '放松': 'to relax; to loosen; to slacken; to unwind; relaxation',
  '故意': 'deliberately; intentionally; on purpose; purposely',
  '数学': 'mathematics; math',
  '斤': 'jin (unit of weight, 0.5 kg); catty; weight',
  '新年': 'New Year; new year',
  '新闻': 'news; current affairs; journalism',
  '新鲜': 'fresh; new; novel; unusual; rare; refreshing',
  '方便面': 'instant noodles',
  '旧': 'old; former; used; worn; previous; past',
  '晚会': 'evening party; gala; social evening; evening event',
  '晚点': 'late; behind schedule; delayed',
  '有关': 'related to; concerning; relevant; to have something to do with',
  '有用': 'useful; helpful; beneficial; of use',
  '服务': 'to serve; service; to provide service',
  '本科': 'undergraduate; bachelor\'s degree; regular college course',
  '村': 'village; hamlet; rural area; countryside',
  '查找': 'to search for; to look up; to seek; to find',
  '查看': 'to check; to examine; to look over; to inspect; to view',
  '标准': 'standard; criterion; norm; benchmark',
  '树': 'tree; to plant; to cultivate; to set up; to establish',
  '校园': 'campus; schoolyard; school grounds',
  '校长': 'principal; headmaster; school president; chancellor',
  '检票': 'to check tickets; to inspect tickets; ticket inspection',
  '棒': 'stick; club; baton; excellent; great; wonderful; capable',
  '楼梯': 'stairs; staircase; stairway',
  '歌声': 'sound of singing; singing voice; song',
  '歌手': 'singer; vocalist',
  '此外': 'besides; in addition; moreover; furthermore; apart from this',
  '此次': 'this time; this occasion; on this occasion',
  '步': 'step; pace; stage; measure word for steps; to walk; on foot',
  '段': 'section; segment; paragraph; period (of time); measure word',
  '毕业': 'to graduate; graduation; to finish school',
  '毕业生': 'graduate; graduating student',
  '毛': 'hair; feather; fur; wool; dime (0.1 yuan); gross; rough; careless',
  '汗': 'sweat; perspiration',
  '法': 'law; method; way; principle; rule; France; Buddhist teaching',
  '洗衣机': 'washing machine; laundry machine',
  '游客': 'tourist; visitor; sightseer; traveler',
  '游戏': 'game; to play; recreation; amusement',
  '点名': 'to call roll; to take attendance; to mention by name; to name',
  '点头': 'to nod; to nod one\'s head; to agree by nodding',
  '烦': 'annoyed; irritated; vexed; to trouble; to bother; tedious',
  '烦恼': 'worried; troubled; vexed; annoyed; trouble; worry; vexation',
  '热情': 'enthusiastic; warm; passionate; warmhearted; cordial; zeal',
  '爬': 'to crawl; to climb; to clamber; to scramble; to creep',
  '爱心': 'love; compassion; kindness; caring heart; charity',
  '爱情': 'love; romantic love; affection',
  '父女': 'father and daughter',
  '父子': 'father and son',
  '牙': 'tooth; ivory; tusk; tooth-like thing',
  '牙刷': 'toothbrush',
  '牛': 'cow; ox; cattle; bull; awesome; powerful; arrogant',
  '特别': 'special; particular; unusual; especially; extraordinarily',
  '猜': 'to guess; to suspect; to conjecture; to speculate',
  '球场': 'sports field; court; pitch; ground (for ball games)',
  '瓶子': 'bottle; vase; jar; flask',
  '甜': 'sweet; pleasant; comfortable; sound (sleep); honeyed',
  '电动车': 'electric bicycle; electric vehicle; e-bike; electric car',
  '电视剧': 'TV drama; television series; TV show',
  '男生': 'male student; schoolboy; boy; young man',
  '画家': 'painter; artist',
  '留学生': 'international student; student studying abroad; exchange student',
  '瘦': 'thin; lean; slim; tight; not fertile',
  '登机': 'to board a plane; to check in (at airport)',
  '白酒': 'white liquor; baijiu (Chinese distilled spirit)',
  '相机': 'camera; photographic camera',
  '短信': 'text message; short message; SMS',
  '短裤': 'shorts; short pants',
  '碗': 'bowl; measure word for bowls of food',
  '秋天': 'autumn; fall; fall season',
  '空调': 'air conditioning; air conditioner; AC',
  '窗': 'window; opening in a wall',
  '笔试': 'written examination; written test; paper test',
  '笨': 'stupid; foolish; clumsy; dull; awkward; slow-witted',
  '等到': 'to wait until; by the time; when; until',
  '答': 'to answer; to reply; to respond; to reciprocate; to repay',
  '答应': 'to promise; to agree; to answer; to respond; to consent',
  '粗': 'thick; coarse; rough; crude; wide; vulgar; careless',
  '粗心': 'careless; thoughtless; negligent; inattentive',
  '糖': 'sugar; sweets; candy; carbohydrate',
  '红绿灯': 'traffic lights; traffic signal',
  '练': 'to practice; to train; to drill; to exercise; to perfect',
  '经理': 'manager; director; executive; to manage; to handle',
  '结婚': 'to get married; to marry; marriage; wedding',
  '网站': 'website; web site; Internet site',
  '羊': 'sheep; goat; lamb',
  '羽毛球': 'badminton; shuttlecock',
  '而': 'and; yet; while; but; as well as; moreover; and then',
  '而且': 'and; moreover; furthermore; in addition; besides; also',
  '耳机': 'headphones; earphones; earpiece; headset',
  '聊': 'to chat; to talk; to have a conversation; to discuss; merely; briefly',
  '背': 'to carry on the back; to shoulder; back (of body); to recite; to learn by heart; to turn away',
  '背包': 'backpack; knapsack; rucksack',
  '腿': 'leg; thigh; lower limb; leg (of furniture)',
  '茶叶': 'tea leaves; tea; tea products',
  '蓝': 'blue; indigo plant; blueness',
  '街': 'street; road; market; fair',
  '表': 'watch; surface; to show; to express; form; table; list; meter; gauge; exterior',
  '表格': 'form; table; chart; spreadsheet',
  '袋子': 'bag; sack; pouch; plastic bag',
  '裙子': 'skirt; dress',
  '西': 'west; western; occidental',
  '西北': 'northwest; northwestern',
  '西南': 'southwest; southwestern',
  '西方': 'the West; western; west; the Occident; Western countries',
  '西瓜': 'watermelon',
  '要求': 'requirement; to request; to demand; to require; to ask for',
  '观看': 'to watch; to view; to observe; to look at',
  '角': 'horn; angle; corner; dime (0.1 yuan); role; character',
  '订': 'to subscribe; to book; to order; to reserve; to agree on; to conclude',
  '认为': 'to think; to believe; to consider; to regard; to hold the view',
  '认得': 'to recognize; to know; to be acquainted with; to remember',
  '词语': 'word and expression; term; vocabulary; phrase',
  '诚实': 'honest; truthful; sincere; honesty; integrity',
  '语言': 'language; speech; linguistic',
  '读者': 'reader; readership',
  '课文': 'text (of a lesson); lesson text; reading passage',
  '课本': 'textbook; coursebook; class book',
  '负责': 'to be responsible for; to be in charge of; responsible; conscientious',
  '负责人': 'person in charge; responsible person; head; leader',
  '购买': 'to purchase; to buy; to acquire',
  '购物': 'to shop; shopping; to go shopping; to purchase goods',
  '费': 'fee; expense; cost; to spend; to cost; to waste; to consume',
  '赶上': 'to catch up with; to overtake; to be in time for; to happen to encounter',
  '赶快': 'hurriedly; quickly; at once; immediately; right away',
  '赶紧': 'hurriedly; quickly; without delay; hastily; at once',
  '起': 'to rise; to get up; to start; to stand up; to raise; to build; to draft',
  '起飞': 'to take off (aircraft); to launch; takeoff',
  '越': 'to exceed; to climb over; to surpass; the more...the more; Vietnam',
  '路口': 'intersection; crossing; crossroads; street junction',
  '路边': 'roadside; curb; edge of the road',
  '身高': 'height (of a person); stature; body height',
  '车位': 'parking space; parking spot; parking place',
  '车速': 'vehicle speed; speed of a car',
  '转机': 'to transfer (flights); connecting flight; transit; a turn for the better',
  '辆': 'measure word for vehicles/cars/bicycles',
  '过节': 'to celebrate a festival/holiday; to spend a holiday',
  '运动会': 'sports meet; athletic meeting; games; sports competition',
  '迟': 'late; delayed; slow; tardy; to delay',
  '遇到': 'to meet; to encounter; to run into; to come across',
  '遇见': 'to meet; to encounter; to come across; to run into',
  '道': 'road; path; way; principle; doctrine; Taoism; to say; to speak; measure word',
  '道歉': 'to apologize; apology; to make an apology; to say sorry',
  '道路': 'road; path; way; route; pathway',
  '邮箱': 'mailbox; email inbox; postbox; letter box',
  '部': 'part; section; unit; department; ministry; measure word for films/books; troops',
  '酒': 'alcohol; liquor; wine; spirits; alcoholic beverage',
  '钢琴': 'piano',
  '银行': 'bank',
  '银行卡': 'bank card; ATM card; debit card',
  '错过': 'to miss; to let slip; to overlook; to miss out on',
  '队': 'team; group; squad; line; queue; rank; formation',
  '队员': 'team member; squad member; player',
  '队长': 'team leader; team captain; squad leader',
  '附近': 'nearby; vicinity; neighborhood; close to; in the vicinity of',
  '难听': 'unpleasant to hear; harsh-sounding; offensive; ugly (words)',
  '难看': 'ugly; unsightly; bad-looking; embarrassing; disgraceful',
  '难过': 'sad; unhappy; sorrowful; to feel upset; to have a hard time',
  '难题': 'difficult problem; challenge; hard question; tough issue',
  '雨衣': 'raincoat; waterproof clothing',
  '面前': 'in front of; in the face of; facing; before; in the presence of',
  '页': 'page; leaf; sheet',
  '顾客': 'customer; client; shopper; patron',
  '顿': 'measure word for meals, beatings, scoldings, etc.; to pause; to stop; suddenly',
  '风': 'wind; breeze; style; manner; custom; practice; news; scene',
  '饮料': 'beverage; drink; refreshment',
  '香蕉': 'banana',
  '马路': 'road; street; avenue; highway',
  '高于': 'higher than; above; exceeding; greater than',
  '高价': 'high price; expensive',
  '高温': 'high temperature; hot weather',
  '高考': 'college entrance examination; university entrance exam',
  '高速': 'high speed; expressway; highway; high-speed',
  '高铁': 'high-speed rail; high-speed train; bullet train',
  '鸡': 'chicken; fowl; rooster',
  '黑板': 'blackboard; chalkboard',
  '鼻子': 'nose',
};

module.exports = dict;