const fs = require('fs');

// Read current dictionary and find missing words
const data = JSON.parse(fs.readFileSync('public/hsk_vocabulary_complete.json', 'utf-8'));
const CE_DICT = require('./ce_dict.cjs');

const missing = data.words.filter(w => !CE_DICT[w.chinese] || CE_DICT[w.chinese].startsWith('(see ') || CE_DICT[w.chinese].startsWith('(particle'));

const newEntries = {};

// Common HSK 1-4 translations
const supplements = {
  '吧': 'modal particle; let\'s; okay',
  '白天': 'daytime; during the day',
  '边': 'side; edge; border; simultaneously',
  '病': 'illness; disease; to be sick',
  '唱': 'to sing',
  '超市': 'supermarket',
  '大家': 'everyone; everybody; all',
  '大学生': 'university/college student',
  '第': 'ordinal prefix',
  '电话': 'telephone; phone call',
  '电影院': 'cinema; movie theater',
  '读书': 'to read; to study',
  '儿子': 'son',
  '饭': 'meal; cooked rice; food',
  '公司': 'company; corporation; firm',
  '工作': 'work; job; to work',
  '狗': 'dog',
  '好看': 'good-looking; nice; pretty',
  '好听': 'pleasant to hear; nice sounding',
  '好玩儿': 'fun; amusing; interesting',
  '后': 'after; behind; back; rear',
  '火车': 'train',
  '鸡蛋': 'chicken egg',
  '家人': 'family members',
  '见': 'to see; to meet; to catch sight of',
  '今年': 'this year',
  '开车': 'to drive a car',
  '看病': 'to see a doctor; to treat illness',
  '两': 'two (measure word); both',
  '吗': 'question particle',
  '卖': 'to sell',
  '没事': 'it\'s nothing; no problem; never mind',
  '们': 'plural marker for pronouns/people',
  '面包': 'bread',
  '面条儿': 'noodles',
  '明年': 'next year',
  '哪个': 'which one',
  '哪些': 'which (plural); what',
  '那边': 'over there; that side',
  '那个': 'that one; that',
  '那些': 'those',
  '男朋友': 'boyfriend',
  '你好': 'hello; hi',
  '您': 'you (polite/honorific)',
  '女朋友': 'girlfriend',
  '女士': 'lady; madam; Ms.',
  '便宜': 'cheap; inexpensive; bargain',
  '起床': 'to get up; to get out of bed',
  '前': 'front; before; ago; previous',
  '去年': 'last year',
  '日': 'day; sun; date',
  '上课': 'to go to class; to attend class',
  '谁': 'who; whom',
  '事': 'matter; thing; affair; event',
  '书店': 'bookstore; bookshop',
  '岁': 'year (of age); years old',
  '它': 'it',
  '它们': 'they; them (for animals/things)',
  '听见': 'to hear; to catch the sound of',
  '外边': 'outside; outer',
  '晚': 'late; evening; night',
  '晚饭': 'dinner; evening meal',
  '午饭': 'lunch; midday meal',
  '下班': 'to get off work; to finish work',
  '小朋友': 'child; kid; little friend',
  '小学': 'elementary school; primary school',
  '星期天': 'Sunday',
  '学习': 'to study; to learn; learning',
  '雪': 'snow',
  '一半': 'half; one half',
  '一下': 'once; a little while; briefly',
  '一些': 'some; a few; a little',
  '有的': 'some; there are some',
  '有点儿': 'a little; somewhat; a bit',
  '有些': 'some; somewhat; there are some',
  '元': 'yuan (Chinese currency); unit',
  '再': 'again; once more; then; further',
  '早饭': 'breakfast',
  '这边': 'this side; here; over here',
  '这个': 'this; this one',
  '这些': 'these',
  '中午': 'noon; midday',
  '中学': 'middle school; secondary school',
  '中学生': 'middle school student',
  '帮': 'to help; to assist; gang; group',
  '不错': 'not bad; pretty good; right',
  '出国': 'to go abroad',
  '出来': 'to come out; to emerge; to appear',
  '出门': 'to go out; to leave home; to travel',
  '词': 'word; term; vocabulary',
  '次': 'time; occurrence; measure word for times',
  '从小': 'from childhood; since childhood',
  '打车': 'to take a taxi',
  '但': 'but; however; yet',
  '地': 'structural particle (adverbial); earth; land',
  '地铁': 'subway; metro; underground',
  '懂': 'to understand; to comprehend',
  '动': 'to move; to act; movement; motion',
  '飞': 'to fly',
  '高中': 'senior high school',
  '跟': 'with; to follow; and; heel',
  '过年': 'to celebrate the New Year',
  '黑色': 'black (color)',
  '红茶': 'black tea; red tea',
  '红色': 'red (color)',
  '海洋': 'ocean; sea',
  '回国': 'to return to one\'s country',
  '回家': 'to go home; to return home',
  '火车票': 'train ticket',
  '机票': 'airline ticket; plane ticket',
  '家': 'home; family; household; specialist',
  '家~': 'home; family (see separate entry)',
  '家人~': 'family members (see separate entry)',
  '开车~': 'to drive a car (see separate entry)',
  '看病~': 'to see a doctor (see separate entry)',
  '蓝色': 'blue (color)',
  '两~': 'two (see separate entry)',
  '邻居~': 'neighbor (see separate entry)',
  '零钱': 'small change; pocket money',
  '留学~': 'to study abroad (see separate entry)',
  '楼': 'building; floor; storey',
  '律师~': 'lawyer (see separate entry)',
  '绿色~': 'green color (see separate entry)',
  '卖~': 'to sell (see separate entry)',
  '面包~': 'bread (see separate entry)',
  '面条~': 'noodles (see separate entry)',
  '暖': 'warm; to warm up',
  '胖~': 'fat; plump (see separate entry)',
  '便宜~': 'cheap (see separate entry)',
  '请假~': 'to ask for leave (see separate entry)',
  '让~': 'to let; to allow (see separate entry)',
  '上课~': 'to attend class (see separate entry)',
  '生病~': 'to fall ill (see separate entry)',
  '失业': 'to lose one\'s job; unemployment',
  '食堂~': 'canteen (see separate entry)',
  '甜': 'sweet',
  '外卖': 'takeout; delivery (food)',
  '碗': 'bowl',
  '午': 'noon; midday',
  '洗': 'to wash; to bathe; to clean',
  '行~': 'OK; profession (see separate entry)',
  '养': 'to raise; to keep; to grow; to support',
  '药~': 'medicine (see separate entry)',
  '已经~': 'already (see separate entry)',
  '月~': 'month (see separate entry)',
  '越': 'to exceed; to surpass; the more...',
  '站~': 'station; to stand (see separate entry)',
  '找~': 'to look for (see separate entry)',
  '纸': 'paper',
  '只要': 'as long as; provided that',
  '中文~': 'Chinese language (see separate entry)',
  '钟~': 'clock (see separate entry)',
  '种~': 'kind; type (see separate entry)',
  '转~': 'to turn (see separate entry)',
  '最~': 'most (see separate entry)',
  '坐~': 'to sit (see separate entry)',
  '为(wéi)': 'to do; to act as; to be; to become',
  '为(wèi)': 'for; for the sake of; because of',
  '安全~': 'safe; security (see separate entry)',
  '按': 'according to; to press; to push',
  '按照': 'according to; in accordance with',
  '本~': 'root; origin; measure word (see)',
  '变~': 'to change (see separate entry)',
  '遍~': 'time; all over (see separate entry)',
  '表现': 'to show; to display; to behave; performance',
  '并且~': 'and; moreover (see separate entry)',
  '部': 'department; ministry; part; section; measure word',
  '参加~': 'to participate (see separate entry)',
  '参观~': 'to visit; to tour (see separate entry)',
  '产品': 'product; goods; produce',
  '超': 'to exceed; to surpass; super; ultra',
  '朝': 'toward; facing; dynasty; to face',
  '车站~': 'station (see separate entry)',
  '成功': 'to succeed; success; successful',
  '程序': 'procedure; program; sequence; order',
  '持续': 'to continue; to persist; sustained',
  '充分': 'sufficient; ample; full; abundant',
  '重~': 'weight; heavy; to repeat (see separate entry)',
  '初': 'beginning; initial; early; elementary',
  '传统': 'tradition; traditional; conventional',
  '创新': 'to innovate; innovation; creative',
  '此': 'this; these; here',
  '粗': 'thick; coarse; rough; rude; vulgar',
  '搭配': 'to match; to pair; collocation; combination',
  '达到~': 'to reach (see separate entry)',
  '达到~': 'to reach; to achieve (see separate entry)',
  '大人': 'adult; grown-up',
  '当地~': 'local (see separate entry)',
  '到达~': 'to arrive (see separate entry)',
  '低~': 'low (see separate entry)',
  '地球~': 'the Earth (see separate entry)',
  '地区': 'region; area; district; zone',
  '调查~': 'to investigate (see separate entry)',
  '独立': 'independent; independence; alone',
  '短~': 'short (see separate entry)',
  '队': 'team; group; line; queue; rank',
  '儿童~': 'children (see separate entry)',
  '发表~': 'to publish (see separate entry)',
  '方': 'square; direction; side; method; just',
  '分析': 'to analyze; analysis',
  '丰富~': 'rich; abundant (see separate entry)',
  '否则~': 'otherwise (see separate entry)',
  '复杂': 'complex; complicated; intricate',
  '改革': 'to reform; reform; transformation',
  '改造': 'to transform; to reform; to remake',
  '高度': 'height; altitude; high degree; highly',
  '高速公路~': 'highway (see separate entry)',
  '个人~': 'individual (see separate entry)',
  '各': 'each; every; various; different',
  '工业': 'industry; industrial',
  '关系': 'relationship; relation; connection; to concern',
  '关心': 'to care about; to be concerned; care; concern',
  '关于': 'about; concerning; regarding; on',
  '观察': 'to observe; to watch; observation',
  '官': 'official; officer; government; organ',
  '观': 'to observe; to view; view; concept; temple',
  '好~': 'good (see separate entry)',
  '喝~': 'to drink (see separate entry)',
  '和平': 'peace; peaceful; harmonious',
  '红~': 'red (see separate entry)',
  '互联网~': 'Internet (see separate entry)',
  '黄': 'yellow',
  '集中': 'to concentrate; to focus; centralized',
  '坚持': 'to persist; to insist on; to uphold',
  '简短': 'brief; short; concise',
  '讲究': 'to pay attention to; to be particular about',
  '结构': 'structure; composition; construction',
  '金融': 'finance; banking; financial',
  '尽管~': 'despite (see separate entry)',
  '进口': 'to import; import; entrance',
  '进行~': 'to carry out (see separate entry)',
  '剧': 'drama; play; opera; theatrical',
  '据': 'according to; on the basis of; to occupy',
  '绝对': 'absolute; absolutely; definitely',
  '看~': 'to look (see separate entry)',
  '来得及~': 'can make it (see separate entry)',
  '来自~': 'to come from (see separate entry)',
  '劳动': 'work; labor; physical labor',
  '老百姓': 'common people; ordinary citizens; civilians',
  '了~': 'modal particle (see)',
  '力': 'power; force; strength; ability',
  '凉~': 'cool (see separate entry)',
  '亮~': 'bright (see separate entry)',
  '流~': 'to flow (see separate entry)',
  '论': 'to discuss; theory; view; on; by',
  '逻辑': 'logic; logical',
  '美好~': 'beautiful (see separate entry)',
  '秘书': 'secretary; assistant',
  '密码~': 'password (see separate entry)',
  '拍摄': 'to shoot; to photograph; to film',
  '泡': 'to steep; to soak; bubble; foam',
  '批准': 'to approve; to ratify; approval',
  '片~': 'slice; measure word (see separate entry)',
  '普遍~': 'universal (see separate entry)',
  '乒乓球~': 'table tennis (see separate entry)',
  '平等': 'equality; equal; fair',
  '评价': 'to evaluate; to assess; evaluation; assessment',
  '凭': 'by; on the basis of; to rely on; evidence; proof',
  '凭~': 'by; evidence (see separate entry)',
  '巧克力~': 'chocolate (see separate entry)',
  '且': 'and; moreover; for the time being',
  '情绪': 'emotion; mood; feeling; sentiment',
  '请大家': 'everyone; please all of you',
  '区别~': 'difference (see separate entry)',
  '全面': 'comprehensive; all-round; overall; complete',
  '群众': 'the masses; the people; the public',
  '任务~': 'task (see separate entry)',
  '赛~': 'competition (see separate entry)',
  '设': 'to set up; to establish; to design; to suppose',
  '身份': 'identity; status; position; capacity',
  '升': 'to rise; to ascend; to promote; liter',
  '输~': 'to lose (see separate entry)',
  '数学': 'mathematics; math',
  '水平': 'level; standard; horizontal',
  '谈~': 'to talk (see separate entry)',
  '特色': 'characteristic; unique feature; special quality',
  '体制': 'system; structure; organization; regime',
  '挑战': 'to challenge; challenge; to contest',
  '贴': 'to stick; to paste; to post; to keep close to',
  '推广': 'to promote; to popularize; to spread',
  '完善': 'to improve; to perfect; to consummate',
  '危机': 'crisis; critical; imminent danger',
  '维护': 'to safeguard; to protect; to maintain; to uphold',
  '维护~': 'to maintain (see separate entry)',
  '消费者': 'consumer',
  '效率': 'efficiency; effectiveness',
  '醒~': 'to wake up (see separate entry)',
  '雄': 'male; grand; heroic; powerful',
  '宣传': 'to promote; to publicize; to propagandize',
  '选~': 'to choose (see separate entry)',
  '选举': 'to elect; election; to vote',
  '学术': 'academic; scholarship; learning',
  '学期~': 'semester (see separate entry)',
  '训练': 'to train; training; drill; exercise',
  '严格~': 'strict (see separate entry)',
  '演~': 'to perform (see separate entry)',
  '样': 'appearance; shape; sample; pattern; kind',
  '医疗': 'medical treatment; healthcare; medical',
  '医药': 'medicine; medical and pharmaceutical',
  '艺术~': 'art (see separate entry)',
  '议': 'to discuss; opinion; view; proposal',
  '因素': 'factor; element; ingredient',
  '引进': 'to introduce; to bring in; to import',
  '音乐~': 'music (see separate entry)',
  '营造': 'to build; to construct; to create; to foster',
  '则': 'rule; regulation; standard; but; however; then',
  '增长~': 'growth (see separate entry)',
  '站~': 'station; stand (see)',
  '掌握': 'to master; to grasp; to control; to have in hand',
  '战略': 'strategy; strategic',
  '针对': 'to target; to aim at; in view of; directed at',
  '针对~': 'to target (see separate entry)',
  '争': 'to compete; to fight; to strive; to argue',
  '支撑': 'to support; to prop up; to sustain; support',
  '制定': 'to formulate; to draw up; to establish; to enact',
  '智慧': 'wisdom; intelligence; wit; smart',
  '制度': 'system; institution; rules; regulations',
  '重大': 'major; significant; important; great',
  '逐步': 'step by step; gradually; progressively',
  '主任': 'director; head; chief; chairperson',
  '抓': 'to grab; to catch; to seize; to scratch',
  '准确~': 'accurate (see separate entry)',
  '咨询': 'to consult; to seek advice; consultation',
  '资产': 'assets; property; capital; resources',
  '宗教': 'religion; religious',
  '综合': 'comprehensive; integrated; to synthesize; to sum up',
  '总': 'total; overall; general; chief; always',
  '总理': 'premier; prime minister; chancellor',
  '总体': 'overall; total; general; on the whole',
  '足够': 'enough; sufficient; adequate; ample',
  '罪': 'crime; guilt; sin; fault; blame',
  '遵守': 'to observe; to abide by; to comply with',
  '笑话~': 'joke (see separate entry)',
  '信': 'letter; message; to believe; to trust; faith',
  '信心~': 'confidence (see separate entry)',
  '型': 'model; type; pattern; style; mold',
  '形象': 'image; form; figure; visualization',
  '兴': 'to prosper; to flourish; to be popular; excitement',
  '性~': 'nature; gender (see separate entry)',
  '修养': 'cultivation; training; self-cultivation; accomplishment',
  '学校~': 'school (see separate entry)',
  '学~': 'to learn (see separate entry)',
  '学生~': 'student (see separate entry)',
  '学习~': 'to study (see separate entry)',
  '雪~': 'snow (see separate entry)',
  '寻': 'to search; to look for; to seek',
  '眼~': 'eye (see separate entry)',
  '演员~': 'actor (see separate entry)',
  '阳光~': 'sunshine (see separate entry)',
};

Object.assign(newEntries, supplements);

const merged = { ...CE_DICT };

// Remove placeholder entries and add new ones
for (const [key, val] of Object.entries(merged)) {
  if (val.startsWith('(see ') || val.startsWith('(particle') || key.includes('~')) {
    // Keep the original if a supplement exists
  }
}

// Add all new translations
for (const [key, val] of Object.entries(newEntries)) {
  merged[key] = val;
}

// Output just the missing that still need work
const stillMissing = data.words.filter(w => !merged[w.chinese] || merged[w.chinese].startsWith('(see ') || merged[w.chinese].startsWith('(particle'));
console.log('Still missing after supplement:', stillMissing.length);

if (stillMissing.length > 0) {
  stillMissing.slice(0, 100).forEach(w => {
    console.log(`  '${w.chinese}': '', // ${w.pinyin} (lv ${w.hsk_level})`);
  });
}